/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Veiculo;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CadastroVEI_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CadastroVEI_GUI
     */
    public CadastroVEI_GUI() {
        initComponents();
        nome_txt.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        VOLTAR_BTN = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel6 = new javax.swing.JLabel();
        placa_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel7 = new javax.swing.JLabel();
        modelo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel8 = new javax.swing.JLabel();
        marca_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel9 = new javax.swing.JLabel();
        cor_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel10 = new javax.swing.JLabel();
        tipo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel13 = new javax.swing.JLabel();
        categoria_txt = new org.edisoncor.gui.textField.TextFieldRound();
        LIMPAR_BTN = new org.edisoncor.gui.button.ButtonRound();
        CADASTRARVEI_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nome_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel19 = new javax.swing.JLabel();
        doc_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel20 = new javax.swing.JLabel();
        contato_txt = new org.edisoncor.gui.textField.TextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 74), 4, true));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("C A D A S T R O");

        VOLTAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/voltar_img.png"))); // NOI18N
        VOLTAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLTAR_BTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VOLTAR_BTNLayout = new javax.swing.GroupLayout(VOLTAR_BTN);
        VOLTAR_BTN.setLayout(VOLTAR_BTNLayout);
        VOLTAR_BTNLayout.setHorizontalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        VOLTAR_BTNLayout.setVerticalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(4, 4, 792, 80);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.rodape_img.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(4, 496, 792, 100);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Placa:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 320, 50, 24);

        placa_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa_txtActionPerformed(evt);
            }
        });
        placa_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                placa_txtKeyPressed(evt);
            }
        });
        jPanel1.add(placa_txt);
        placa_txt.setBounds(120, 320, 125, 24);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Modelo:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 380, 60, 24);

        modelo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelo_txtActionPerformed(evt);
            }
        });
        modelo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modelo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(modelo_txt);
        modelo_txt.setBounds(120, 380, 125, 24);

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tipo:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(520, 320, 60, 24);

        marca_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marca_txtActionPerformed(evt);
            }
        });
        marca_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                marca_txtKeyPressed(evt);
            }
        });
        jPanel1.add(marca_txt);
        marca_txt.setBounds(350, 320, 125, 24);

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Marca:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 320, 70, 24);

        cor_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cor_txtActionPerformed(evt);
            }
        });
        cor_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cor_txtKeyPressed(evt);
            }
        });
        jPanel1.add(cor_txt);
        cor_txt.setBounds(350, 380, 125, 24);

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cor:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(300, 380, 30, 24);

        tipo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_txtActionPerformed(evt);
            }
        });
        tipo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(tipo_txt);
        tipo_txt.setBounds(590, 320, 125, 24);

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Categoria:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(491, 380, 80, 24);

        categoria_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoria_txtActionPerformed(evt);
            }
        });
        categoria_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                categoria_txtKeyPressed(evt);
            }
        });
        jPanel1.add(categoria_txt);
        categoria_txt.setBounds(590, 380, 125, 24);

        LIMPAR_BTN.setBackground(new java.awt.Color(33, 63, 110));
        LIMPAR_BTN.setText("LIMPAR");
        LIMPAR_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        LIMPAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LIMPAR_BTNMouseEntered(evt);
            }
        });
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(150, 440, 150, 35);

        CADASTRARVEI_BTN.setBackground(new java.awt.Color(33, 63, 110));
        CADASTRARVEI_BTN.setText("CADASTRAR");
        CADASTRARVEI_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        CADASTRARVEI_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CADASTRARVEI_BTNMouseEntered(evt);
            }
        });
        CADASTRARVEI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTRARVEI_BTNActionPerformed(evt);
            }
        });
        CADASTRARVEI_BTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CADASTRARVEI_BTNKeyPressed(evt);
            }
        });
        jPanel1.add(CADASTRARVEI_BTN);
        CADASTRARVEI_BTN.setBounds(480, 440, 150, 35);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VEÍCULO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 260, 97, 24);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PROPRIETÁRIO");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(330, 130, 170, 24);

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nome:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(280, 190, 50, 24);

        nome_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_txtActionPerformed(evt);
            }
        });
        nome_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nome_txtKeyPressed(evt);
            }
        });
        jPanel1.add(nome_txt);
        nome_txt.setBounds(350, 190, 125, 24);

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("*CPF:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(40, 190, 70, 24);

        doc_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_txtActionPerformed(evt);
            }
        });
        doc_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                doc_txtKeyPressed(evt);
            }
        });
        jPanel1.add(doc_txt);
        doc_txt.setBounds(120, 190, 125, 24);

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Contato:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(510, 190, 60, 24);

        contato_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contato_txtActionPerformed(evt);
            }
        });
        contato_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contato_txtKeyPressed(evt);
            }
        });
        jPanel1.add(contato_txt);
        contato_txt.setBounds(590, 190, 125, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VOLTAR_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTAR_BTNMouseClicked
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTAR_BTNMouseClicked

    private void placa_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placa_txtActionPerformed

    private void placa_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placa_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            modelo_txt.requestFocus();
        }
    }//GEN-LAST:event_placa_txtKeyPressed

    private void modelo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelo_txtActionPerformed

    private void modelo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelo_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            marca_txt.requestFocus();
        }
    }//GEN-LAST:event_modelo_txtKeyPressed

    private void marca_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marca_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marca_txtActionPerformed

    private void marca_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marca_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            cor_txt.requestFocus();
        }
    }//GEN-LAST:event_marca_txtKeyPressed

    private void cor_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cor_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cor_txtActionPerformed

    private void cor_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cor_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            tipo_txt.requestFocus();
        }
    }//GEN-LAST:event_cor_txtKeyPressed

    private void tipo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_txtActionPerformed

    private void tipo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipo_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
       categoria_txt.requestFocus();
        }
    }//GEN-LAST:event_tipo_txtKeyPressed

    private void categoria_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoria_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria_txtActionPerformed

    private void categoria_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoria_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            CADASTRARVEI_BTN.doClick();
        }
    }//GEN-LAST:event_categoria_txtKeyPressed

    private void LIMPAR_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIMPAR_BTNMouseEntered
        LIMPAR_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LIMPAR_BTNMouseEntered

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        placa_txt.setText("");
        modelo_txt.setText("");
        marca_txt.setText("");
        categoria_txt.setText("");
        tipo_txt.setText("");
        cor_txt.setText("");
        nome_txt.setText("");
        doc_txt.setText("");
        contato_txt.setText("");
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    private void CADASTRARVEI_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CADASTRARVEI_BTNMouseEntered
        CADASTRARVEI_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CADASTRARVEI_BTNMouseEntered

    private void CADASTRARVEI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTRARVEI_BTNActionPerformed
        String nome = nome_txt.getText().trim();
    String doc = doc_txt.getText().trim();
    String contato = contato_txt.getText().trim();

    String placa = placa_txt.getText().trim();
    String modelo = modelo_txt.getText().trim();
    String marca = marca_txt.getText().trim();
    String cor = cor_txt.getText().trim();
    String tipo = tipo_txt.getText().trim();
    String categoria = categoria_txt.getText().trim();

    if (nome.isEmpty() || doc.isEmpty() || placa.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        return;
    }

    Veiculo v = new Veiculo();
    v.setNome(nome);
    v.setDocumento(doc);
    v.setContato(contato);
    v.setPlaca(placa);
    v.setModelo(modelo);
    v.setMarca(marca);
    v.setCor(cor);
    v.setTipo(tipo);
    v.setCategoria(categoria);

    boolean cadastrado = Controller.Cadastrar_DAO.cadastrarVeiculo(v);

    if (cadastrado) {
        JOptionPane.showMessageDialog(this, "Veículo cadastrado com sucesso!");
        // Limpa campos
        nome_txt.setText("");
        doc_txt.setText("");
        contato_txt.setText("");
        placa_txt.setText("");
        modelo_txt.setText("");
        marca_txt.setText("");
        cor_txt.setText("");
        tipo_txt.setText("");
        categoria_txt.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar veículo!");
    }
    }//GEN-LAST:event_CADASTRARVEI_BTNActionPerformed

    private void CADASTRARVEI_BTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CADASTRARVEI_BTNKeyPressed

    }//GEN-LAST:event_CADASTRARVEI_BTNKeyPressed

    private void nome_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_txtActionPerformed

    private void nome_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            contato_txt.requestFocus();
        }
    }//GEN-LAST:event_nome_txtKeyPressed

    private void doc_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_txtActionPerformed

    private void doc_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doc_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            nome_txt.requestFocus();
        }
    }//GEN-LAST:event_doc_txtKeyPressed

    private void contato_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contato_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contato_txtActionPerformed

    private void contato_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contato_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            placa_txt.requestFocus();
        }
    }//GEN-LAST:event_contato_txtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVEI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVEI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVEI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVEI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVEI_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound CADASTRARVEI_BTN;
    private org.edisoncor.gui.button.ButtonRound LIMPAR_BTN;
    private org.edisoncor.gui.panel.PanelImage VOLTAR_BTN;
    private org.edisoncor.gui.textField.TextFieldRound categoria_txt;
    private org.edisoncor.gui.textField.TextFieldRound contato_txt;
    private org.edisoncor.gui.textField.TextFieldRound cor_txt;
    private org.edisoncor.gui.textField.TextFieldRound doc_txt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.textField.TextFieldRound marca_txt;
    private org.edisoncor.gui.textField.TextFieldRound modelo_txt;
    private org.edisoncor.gui.textField.TextFieldRound nome_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.textField.TextFieldRound placa_txt;
    private org.edisoncor.gui.textField.TextFieldRound tipo_txt;
    // End of variables declaration//GEN-END:variables
}
