/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Cadastrar_DAO;
import Model.Visitante;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CadastroVI_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_GUI
     */
    String caminhoImagem = "";

    
    public CadastroVI_GUI() {
        initComponents();
        nome_txt.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        VOLTAR_BTN = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel6 = new javax.swing.JLabel();
        nome_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel7 = new javax.swing.JLabel();
        doc_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel8 = new javax.swing.JLabel();
        empresa_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel9 = new javax.swing.JLabel();
        motivo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel10 = new javax.swing.JLabel();
        contato_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel13 = new javax.swing.JLabel();
        colaborador_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel14 = new javax.swing.JLabel();
        LIMPAR_BTN = new org.edisoncor.gui.button.ButtonRound();
        CADASTRARVI_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel5 = new javax.swing.JLabel();
        foto_img = new org.edisoncor.gui.panel.PanelImage();
        FOTO_BTN = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 74), 4, true));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("C A D A S T R O");

        VOLTAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/voltar_img.png"))); // NOI18N
        VOLTAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLTAR_BTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VOLTAR_BTNLayout = new javax.swing.GroupLayout(VOLTAR_BTN);
        VOLTAR_BTN.setLayout(VOLTAR_BTNLayout);
        VOLTAR_BTNLayout.setHorizontalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        VOLTAR_BTNLayout.setVerticalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 80);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.rodape_img.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(4, 496, 792, 100);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nome:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 170, 47, 24);

        nome_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_txtActionPerformed(evt);
            }
        });
        nome_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nome_txtKeyPressed(evt);
            }
        });
        jPanel1.add(nome_txt);
        nome_txt.setBounds(120, 170, 125, 24);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CPF:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 230, 30, 24);

        doc_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_txtActionPerformed(evt);
            }
        });
        doc_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                doc_txtKeyPressed(evt);
            }
        });
        jPanel1.add(doc_txt);
        doc_txt.setBounds(120, 230, 125, 24);

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Contato:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(520, 170, 60, 24);

        empresa_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresa_txtActionPerformed(evt);
            }
        });
        empresa_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empresa_txtKeyPressed(evt);
            }
        });
        jPanel1.add(empresa_txt);
        empresa_txt.setBounds(340, 170, 125, 24);

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Empresa:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(260, 170, 70, 24);

        motivo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motivo_txtActionPerformed(evt);
            }
        });
        motivo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                motivo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(motivo_txt);
        motivo_txt.setBounds(340, 230, 125, 24);

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Motivo:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(270, 230, 60, 24);

        contato_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contato_txtActionPerformed(evt);
            }
        });
        contato_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contato_txtKeyPressed(evt);
            }
        });
        jPanel1.add(contato_txt);
        contato_txt.setBounds(590, 170, 125, 24);

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Colaborador:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(490, 230, 90, 24);

        colaborador_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaborador_txtActionPerformed(evt);
            }
        });
        colaborador_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                colaborador_txtKeyPressed(evt);
            }
        });
        jPanel1.add(colaborador_txt);
        colaborador_txt.setBounds(590, 230, 125, 24);

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("FOTO");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(370, 450, 50, 20);

        LIMPAR_BTN.setBackground(new java.awt.Color(33, 63, 110));
        LIMPAR_BTN.setText("LIMPAR");
        LIMPAR_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        LIMPAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LIMPAR_BTNMouseEntered(evt);
            }
        });
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(150, 440, 150, 35);

        CADASTRARVI_BTN.setBackground(new java.awt.Color(33, 63, 110));
        CADASTRARVI_BTN.setText("CADASTRAR");
        CADASTRARVI_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        CADASTRARVI_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CADASTRARVI_BTNMouseEntered(evt);
            }
        });
        CADASTRARVI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTRARVI_BTNActionPerformed(evt);
            }
        });
        CADASTRARVI_BTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CADASTRARVI_BTNKeyPressed(evt);
            }
        });
        jPanel1.add(CADASTRARVI_BTN);
        CADASTRARVI_BTN.setBounds(480, 440, 150, 35);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VISITANTE");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 110, 118, 24);

        foto_img.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        foto_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/foto_img.png"))); // NOI18N

        javax.swing.GroupLayout foto_imgLayout = new javax.swing.GroupLayout(foto_img);
        foto_img.setLayout(foto_imgLayout);
        foto_imgLayout.setHorizontalGroup(
            foto_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        foto_imgLayout.setVerticalGroup(
            foto_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jPanel1.add(foto_img);
        foto_img.setBounds(340, 290, 100, 100);

        FOTO_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fotobuscar_img.png"))); // NOI18N
        FOTO_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FOTO_BTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FOTO_BTNMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout FOTO_BTNLayout = new javax.swing.GroupLayout(FOTO_BTN);
        FOTO_BTN.setLayout(FOTO_BTNLayout);
        FOTO_BTNLayout.setHorizontalGroup(
            FOTO_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        FOTO_BTNLayout.setVerticalGroup(
            FOTO_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel1.add(FOTO_BTN);
        FOTO_BTN.setBounds(370, 400, 45, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        nome_txt.setText("");
        doc_txt.setText("");
        empresa_txt.setText("");
        colaborador_txt.setText("");
        contato_txt.setText("");
        motivo_txt.setText("");
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    private void CADASTRARVI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTRARVI_BTNActionPerformed
        String nome = nome_txt.getText().trim();
    String doc = doc_txt.getText().trim();
    String empresa = empresa_txt.getText().trim();
    String motivo = motivo_txt.getText().trim();
    String contato = contato_txt.getText().trim();
    String colaborador = colaborador_txt.getText().trim();

    if (nome.isEmpty() || doc.isEmpty() || colaborador.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        return;
    }

    Visitante v = new Visitante();
    v.setNome(nome);
    v.setDocumento(doc);
    v.setEmpresa(empresa);
    v.setMotivo(motivo);
    v.setContato(contato);
    v.setColaborador(colaborador);
    v.setDataEntrada(java.time.LocalDate.now().toString());
    v.setHoraEntrada(java.time.LocalTime.now().withNano(0).toString());
    v.setStatus("Ativo");
    v.setFoto(caminhoImagem); // ✅ salva caminho da imagem

    boolean cadastrado = Controller.Cadastrar_DAO.cadastrarVisitante(v);
    if (cadastrado) {
        JOptionPane.showMessageDialog(this, "Visitante cadastrado com sucesso!");
        nome_txt.setText("");
        doc_txt.setText("");
        empresa_txt.setText("");
        motivo_txt.setText("");
        contato_txt.setText("");
        colaborador_txt.setText("");
        foto_img.setIcon(null);
        caminhoImagem = "";
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar visitante!");
    }
    }//GEN-LAST:event_CADASTRARVI_BTNActionPerformed

    private void CADASTRARVI_BTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CADASTRARVI_BTNKeyPressed

    }//GEN-LAST:event_CADASTRARVI_BTNKeyPressed

    private void VOLTAR_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTAR_BTNMouseClicked
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTAR_BTNMouseClicked

    private void LIMPAR_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIMPAR_BTNMouseEntered
     LIMPAR_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LIMPAR_BTNMouseEntered

    private void CADASTRARVI_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CADASTRARVI_BTNMouseEntered
        CADASTRARVI_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CADASTRARVI_BTNMouseEntered

    private void nome_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_txtActionPerformed

    private void nome_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            doc_txt.requestFocus();
        }
    }//GEN-LAST:event_nome_txtKeyPressed

    private void doc_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_txtActionPerformed

    private void doc_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doc_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            empresa_txt.requestFocus();
        }
    }//GEN-LAST:event_doc_txtKeyPressed

    private void empresa_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresa_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresa_txtActionPerformed

    private void empresa_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empresa_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            motivo_txt.requestFocus();
        }
    }//GEN-LAST:event_empresa_txtKeyPressed

    private void motivo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motivo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motivo_txtActionPerformed

    private void motivo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motivo_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            contato_txt.requestFocus();
        }
    }//GEN-LAST:event_motivo_txtKeyPressed

    private void contato_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contato_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contato_txtActionPerformed

    private void contato_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contato_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            colaborador_txt.requestFocus();
        }
    }//GEN-LAST:event_contato_txtKeyPressed

    private void colaborador_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaborador_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colaborador_txtActionPerformed

    private void colaborador_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colaborador_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            CADASTRARVI_BTN.doClick();
        }
    }//GEN-LAST:event_colaborador_txtKeyPressed

    private void FOTO_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOTO_BTNMouseClicked
         JFileChooser arquivo = new JFileChooser();
    arquivo.setDialogTitle("Selecione uma imagem");
    arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);

    int retorno = arquivo.showOpenDialog(this);
    if (retorno == JFileChooser.APPROVE_OPTION) {
        File file = arquivo.getSelectedFile();
        caminhoImagem = file.getAbsolutePath(); // salva o caminho da imagem

        try {
            // Cria o ImageIcon da imagem selecionada
            ImageIcon icon = new ImageIcon(caminhoImagem);

            // Redimensiona a imagem pro tamanho do PanelImage
            Image imgEscalada = icon.getImage().getScaledInstance(
                foto_img.getWidth(),
                foto_img.getHeight(),
                Image.SCALE_SMOOTH
            );

            // Aplica a imagem no PanelImage
            foto_img.setIcon(new ImageIcon(imgEscalada));

            // Atualiza o painel pra forçar a nova exibição
            foto_img.revalidate();
            foto_img.repaint();

            JOptionPane.showMessageDialog(this, "Imagem carregada com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar imagem: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Nenhuma imagem selecionada.");
    }
    }//GEN-LAST:event_FOTO_BTNMouseClicked

    private void FOTO_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOTO_BTNMouseEntered
        FOTO_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_FOTO_BTNMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVI_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound CADASTRARVI_BTN;
    private org.edisoncor.gui.panel.PanelImage FOTO_BTN;
    private org.edisoncor.gui.button.ButtonRound LIMPAR_BTN;
    private org.edisoncor.gui.panel.PanelImage VOLTAR_BTN;
    private org.edisoncor.gui.textField.TextFieldRound colaborador_txt;
    private org.edisoncor.gui.textField.TextFieldRound contato_txt;
    private org.edisoncor.gui.textField.TextFieldRound doc_txt;
    private org.edisoncor.gui.textField.TextFieldRound empresa_txt;
    private org.edisoncor.gui.panel.PanelImage foto_img;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.textField.TextFieldRound motivo_txt;
    private org.edisoncor.gui.textField.TextFieldRound nome_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
