/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Consultar_DAO;
import Model.Veiculo;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ConsultaATTVEI_GUI extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaATTVEI_GUI
     */
    public ConsultaATTVEI_GUI() {
        initComponents();
        placa_txt.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("tech_solutions?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        VOLTAR_BTN = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        ALTERARVEI_BTN = new org.edisoncor.gui.button.ButtonRound();
        LIMPAR_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        statusvei_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        CONSULTARVEI_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel11 = new javax.swing.JLabel();
        placa_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel12 = new javax.swing.JLabel();
        marca_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel16 = new javax.swing.JLabel();
        tipo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel17 = new javax.swing.JLabel();
        modelo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel19 = new javax.swing.JLabel();
        cor_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel20 = new javax.swing.JLabel();
        categoria_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel21 = new javax.swing.JLabel();
        nome_txt = new org.edisoncor.gui.textField.TextFieldRound();
        codvei_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel22 = new javax.swing.JLabel();
        horaentradavei_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel23 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dataentradavei_txt = new org.edisoncor.gui.textField.TextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 74), 4, true));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("C O N S U L T A");

        VOLTAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/voltar_img.png"))); // NOI18N
        VOLTAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLTAR_BTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VOLTAR_BTNLayout = new javax.swing.GroupLayout(VOLTAR_BTN);
        VOLTAR_BTN.setLayout(VOLTAR_BTNLayout);
        VOLTAR_BTNLayout.setHorizontalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        VOLTAR_BTNLayout.setVerticalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(4, 4, 792, 80);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.rodape_img.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(4, 496, 792, 100);

        ALTERARVEI_BTN.setBackground(new java.awt.Color(33, 63, 110));
        ALTERARVEI_BTN.setText("ALTERAR");
        ALTERARVEI_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ALTERARVEI_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ALTERARVEI_BTNMouseEntered(evt);
            }
        });
        ALTERARVEI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTERARVEI_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(ALTERARVEI_BTN);
        ALTERARVEI_BTN.setBounds(320, 450, 150, 35);

        LIMPAR_BTN.setBackground(new java.awt.Color(33, 63, 110));
        LIMPAR_BTN.setText("LIMPAR");
        LIMPAR_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        LIMPAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LIMPAR_BTNMouseEntered(evt);
            }
        });
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        LIMPAR_BTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LIMPAR_BTNKeyPressed(evt);
            }
        });
        jPanel1.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(570, 450, 150, 35);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DADOS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 330, 75, 24);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VEÍCULO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 100, 97, 24);

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Status:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(410, 380, 60, 24);

        statusvei_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusvei_txtActionPerformed(evt);
            }
        });
        statusvei_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                statusvei_txtKeyPressed(evt);
            }
        });
        jPanel1.add(statusvei_txt);
        statusvei_txt.setBounds(470, 380, 125, 24);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 780, 90);

        CONSULTARVEI_BTN.setBackground(new java.awt.Color(33, 63, 110));
        CONSULTARVEI_BTN.setText("CONSULTAR");
        CONSULTARVEI_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        CONSULTARVEI_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CONSULTARVEI_BTNMouseEntered(evt);
            }
        });
        CONSULTARVEI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTARVEI_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CONSULTARVEI_BTN);
        CONSULTARVEI_BTN.setBounds(80, 450, 150, 35);

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("*Placa:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 240, 50, 24);

        placa_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa_txtActionPerformed(evt);
            }
        });
        placa_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                placa_txtKeyPressed(evt);
            }
        });
        jPanel1.add(placa_txt);
        placa_txt.setBounds(120, 240, 125, 24);

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Marca:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(270, 240, 70, 24);

        marca_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marca_txtActionPerformed(evt);
            }
        });
        marca_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                marca_txtKeyPressed(evt);
            }
        });
        jPanel1.add(marca_txt);
        marca_txt.setBounds(350, 240, 125, 24);

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Tipo:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(520, 240, 60, 24);

        tipo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_txtActionPerformed(evt);
            }
        });
        tipo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(tipo_txt);
        tipo_txt.setBounds(590, 240, 125, 24);

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Modelo:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(50, 280, 60, 24);

        modelo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelo_txtActionPerformed(evt);
            }
        });
        modelo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modelo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(modelo_txt);
        modelo_txt.setBounds(120, 280, 125, 24);

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Cor:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(300, 280, 30, 24);

        cor_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cor_txtActionPerformed(evt);
            }
        });
        cor_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cor_txtKeyPressed(evt);
            }
        });
        jPanel1.add(cor_txt);
        cor_txt.setBounds(350, 280, 125, 24);

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Categoria:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(490, 280, 80, 24);

        categoria_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoria_txtActionPerformed(evt);
            }
        });
        categoria_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                categoria_txtKeyPressed(evt);
            }
        });
        jPanel1.add(categoria_txt);
        categoria_txt.setBounds(590, 280, 125, 24);

        jLabel21.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Nome:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(220, 380, 60, 24);

        nome_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_txtActionPerformed(evt);
            }
        });
        nome_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nome_txtKeyPressed(evt);
            }
        });
        jPanel1.add(nome_txt);
        nome_txt.setBounds(280, 380, 125, 24);

        codvei_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codvei_txtActionPerformed(evt);
            }
        });
        codvei_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codvei_txtKeyPressed(evt);
            }
        });
        jPanel1.add(codvei_txt);
        codvei_txt.setBounds(90, 380, 125, 24);

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Código:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(20, 380, 60, 24);

        horaentradavei_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaentradavei_txtActionPerformed(evt);
            }
        });
        horaentradavei_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                horaentradavei_txtKeyPressed(evt);
            }
        });
        jPanel1.add(horaentradavei_txt);
        horaentradavei_txt.setBounds(650, 400, 125, 24);

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Hora:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(600, 400, 40, 24);

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Data:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(600, 360, 40, 24);

        dataentradavei_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataentradavei_txtActionPerformed(evt);
            }
        });
        dataentradavei_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dataentradavei_txtKeyPressed(evt);
            }
        });
        jPanel1.add(dataentradavei_txt);
        dataentradavei_txt.setBounds(650, 360, 125, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VOLTAR_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTAR_BTNMouseClicked
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTAR_BTNMouseClicked

    private void ALTERARVEI_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALTERARVEI_BTNMouseEntered
        ALTERARVEI_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ALTERARVEI_BTNMouseEntered

    private void ALTERARVEI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTERARVEI_BTNActionPerformed
        Veiculo v = new Veiculo();
    v.setNome(nome_txt.getText().trim());
    v.setPlaca(placa_txt.getText().trim());
    v.setModelo(modelo_txt.getText().trim());
    v.setMarca(marca_txt.getText().trim());
    v.setCor(cor_txt.getText().trim());
    v.setTipo(tipo_txt.getText().trim());
    v.setCategoria(categoria_txt.getText().trim());
    v.setStatus(statusvei_txt.getText().trim());

    boolean atualizado = Consultar_DAO.atualizarVeiculo(v);
    if (atualizado) {
        JOptionPane.showMessageDialog(this, "Veículo atualizado com sucesso!");
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar veículo!");
    }
    }//GEN-LAST:event_ALTERARVEI_BTNActionPerformed

    private void LIMPAR_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIMPAR_BTNMouseEntered
        LIMPAR_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LIMPAR_BTNMouseEntered

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        new SplashScreenMenu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    private void LIMPAR_BTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LIMPAR_BTNKeyPressed

    }//GEN-LAST:event_LIMPAR_BTNKeyPressed

    private void statusvei_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusvei_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusvei_txtActionPerformed

    private void statusvei_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusvei_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusvei_txtKeyPressed

    private void CONSULTARVEI_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONSULTARVEI_BTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CONSULTARVEI_BTNMouseEntered

    private void CONSULTARVEI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTARVEI_BTNActionPerformed
        String placa = placa_txt.getText().trim();
    if (placa.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe a placa!");
        return;
    }

    Veiculo v = Consultar_DAO.consultarVeiculo(placa);
    if (v != null) {
        nome_txt.setText(v.getNome());
        codvei_txt.setText(String.valueOf(v.getCodigo()));
        placa_txt.setText(v.getPlaca());
        modelo_txt.setText(v.getModelo());
        marca_txt.setText(v.getMarca());
        cor_txt.setText(v.getCor());
        tipo_txt.setText(v.getTipo());
        categoria_txt.setText(v.getCategoria());
        statusvei_txt.setText(v.getStatus());
        dataentradavei_txt.setText(v.getDataEntrada());
        horaentradavei_txt.setText(v.getHoraEntrada());
    } else {
        JOptionPane.showMessageDialog(this, "Veículo não encontrado!");
    }
    }//GEN-LAST:event_CONSULTARVEI_BTNActionPerformed

    private void placa_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placa_txtActionPerformed

    private void placa_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placa_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            modelo_txt.requestFocus();
        }
    }//GEN-LAST:event_placa_txtKeyPressed

    private void marca_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marca_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marca_txtActionPerformed

    private void marca_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marca_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            cor_txt.requestFocus();
        }
    }//GEN-LAST:event_marca_txtKeyPressed

    private void tipo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_txtActionPerformed

    private void tipo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipo_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            categoria_txt.requestFocus();
        }
    }//GEN-LAST:event_tipo_txtKeyPressed

    private void modelo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelo_txtActionPerformed

    private void modelo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelo_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            marca_txt.requestFocus();
        }
    }//GEN-LAST:event_modelo_txtKeyPressed

    private void cor_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cor_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cor_txtActionPerformed

    private void cor_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cor_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            tipo_txt.requestFocus();
        }
    }//GEN-LAST:event_cor_txtKeyPressed

    private void categoria_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoria_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria_txtActionPerformed

    private void categoria_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoria_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            CONSULTARVEI_BTN.doClick();
        }
    }//GEN-LAST:event_categoria_txtKeyPressed

    private void nome_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_txtActionPerformed

    private void nome_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_txtKeyPressed

    private void codvei_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codvei_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codvei_txtActionPerformed

    private void codvei_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codvei_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_codvei_txtKeyPressed

    private void horaentradavei_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaentradavei_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaentradavei_txtActionPerformed

    private void horaentradavei_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horaentradavei_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaentradavei_txtKeyPressed

    private void dataentradavei_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataentradavei_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataentradavei_txtActionPerformed

    private void dataentradavei_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataentradavei_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataentradavei_txtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaATTVEI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaATTVEI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaATTVEI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaATTVEI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaATTVEI_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound ALTERARVEI_BTN;
    private org.edisoncor.gui.button.ButtonRound CONSULTARVEI_BTN;
    private org.edisoncor.gui.button.ButtonRound LIMPAR_BTN;
    private org.edisoncor.gui.panel.PanelImage VOLTAR_BTN;
    private org.edisoncor.gui.textField.TextFieldRound categoria_txt;
    private org.edisoncor.gui.textField.TextFieldRound codvei_txt;
    private org.edisoncor.gui.textField.TextFieldRound cor_txt;
    private org.edisoncor.gui.textField.TextFieldRound dataentradavei_txt;
    private javax.persistence.EntityManager entityManager;
    private org.edisoncor.gui.textField.TextFieldRound horaentradavei_txt;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.textField.TextFieldRound marca_txt;
    private org.edisoncor.gui.textField.TextFieldRound modelo_txt;
    private org.edisoncor.gui.textField.TextFieldRound nome_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.textField.TextFieldRound placa_txt;
    private org.edisoncor.gui.textField.TextFieldRound statusvei_txt;
    private javax.swing.JTable tabela;
    private org.edisoncor.gui.textField.TextFieldRound tipo_txt;
    // End of variables declaration//GEN-END:variables
}
