/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Cadastrar_DAO;
import Controller.Consultar_DAO;
import Model.Visitante;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ConsultaATTVI_GUI extends javax.swing.JFrame {
    private String caminhoImagem = null;

    /**
     * Creates new form ConsultaVI_GUI
     */
    public ConsultaATTVI_GUI() {
        initComponents();
        nome_txt.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("tech_solutions?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        VOLTAR_BTN = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel6 = new javax.swing.JLabel();
        nome_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel7 = new javax.swing.JLabel();
        doc_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel8 = new javax.swing.JLabel();
        empresa_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel9 = new javax.swing.JLabel();
        motivo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel10 = new javax.swing.JLabel();
        contato_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel13 = new javax.swing.JLabel();
        colaborador_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel14 = new javax.swing.JLabel();
        ALTERARVI_BTN = new org.edisoncor.gui.button.ButtonRound();
        LIMPAR_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dataentradavi_txt = new org.edisoncor.gui.textField.TextFieldRound();
        foto_img = new org.edisoncor.gui.panel.PanelImage();
        FOTO_BTN = new org.edisoncor.gui.panel.PanelImage();
        jLabel18 = new javax.swing.JLabel();
        statusvi_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        CONSULTARVI_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel17 = new javax.swing.JLabel();
        codvi_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel16 = new javax.swing.JLabel();
        horaentradavi_txt = new org.edisoncor.gui.textField.TextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 74), 4, true));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("C O N S U L T A");

        VOLTAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/voltar_img.png"))); // NOI18N
        VOLTAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLTAR_BTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VOLTAR_BTNLayout = new javax.swing.GroupLayout(VOLTAR_BTN);
        VOLTAR_BTN.setLayout(VOLTAR_BTNLayout);
        VOLTAR_BTNLayout.setHorizontalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        VOLTAR_BTNLayout.setVerticalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(4, 4, 792, 80);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.rodape_img.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(4, 496, 792, 100);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nome:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 280, 47, 24);

        nome_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_txtActionPerformed(evt);
            }
        });
        nome_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nome_txtKeyPressed(evt);
            }
        });
        jPanel1.add(nome_txt);
        nome_txt.setBounds(120, 280, 125, 24);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("*CPF:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 240, 37, 24);

        doc_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_txtActionPerformed(evt);
            }
        });
        doc_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                doc_txtKeyPressed(evt);
            }
        });
        jPanel1.add(doc_txt);
        doc_txt.setBounds(120, 240, 125, 24);

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Contato:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(520, 240, 60, 24);

        empresa_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresa_txtActionPerformed(evt);
            }
        });
        empresa_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empresa_txtKeyPressed(evt);
            }
        });
        jPanel1.add(empresa_txt);
        empresa_txt.setBounds(340, 240, 125, 24);

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Empresa:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(260, 240, 70, 24);

        motivo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motivo_txtActionPerformed(evt);
            }
        });
        motivo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                motivo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(motivo_txt);
        motivo_txt.setBounds(340, 280, 125, 24);

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Motivo:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(270, 280, 60, 24);

        contato_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contato_txtActionPerformed(evt);
            }
        });
        contato_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contato_txtKeyPressed(evt);
            }
        });
        jPanel1.add(contato_txt);
        contato_txt.setBounds(590, 240, 125, 24);

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Colaborador:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(490, 280, 90, 24);

        colaborador_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaborador_txtActionPerformed(evt);
            }
        });
        colaborador_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                colaborador_txtKeyPressed(evt);
            }
        });
        jPanel1.add(colaborador_txt);
        colaborador_txt.setBounds(590, 280, 125, 24);

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("FOTO");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(690, 470, 50, 20);

        ALTERARVI_BTN.setBackground(new java.awt.Color(33, 63, 110));
        ALTERARVI_BTN.setText("ALTERAR");
        ALTERARVI_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ALTERARVI_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ALTERARVI_BTNMouseEntered(evt);
            }
        });
        ALTERARVI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTERARVI_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(ALTERARVI_BTN);
        ALTERARVI_BTN.setBounds(280, 450, 150, 35);

        LIMPAR_BTN.setBackground(new java.awt.Color(33, 63, 110));
        LIMPAR_BTN.setText("LIMPAR");
        LIMPAR_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        LIMPAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LIMPAR_BTNMouseEntered(evt);
            }
        });
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        LIMPAR_BTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LIMPAR_BTNKeyPressed(evt);
            }
        });
        jPanel1.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(480, 450, 150, 35);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENTRADA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 330, 104, 24);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VISITANTE");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 100, 118, 24);

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Data:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(290, 360, 40, 24);

        dataentradavi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataentradavi_txtActionPerformed(evt);
            }
        });
        dataentradavi_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dataentradavi_txtKeyPressed(evt);
            }
        });
        jPanel1.add(dataentradavi_txt);
        dataentradavi_txt.setBounds(340, 360, 125, 24);

        foto_img.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        foto_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/foto_img.png"))); // NOI18N

        javax.swing.GroupLayout foto_imgLayout = new javax.swing.GroupLayout(foto_img);
        foto_img.setLayout(foto_imgLayout);
        foto_imgLayout.setHorizontalGroup(
            foto_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        foto_imgLayout.setVerticalGroup(
            foto_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jPanel1.add(foto_img);
        foto_img.setBounds(660, 310, 100, 100);

        FOTO_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fotoatt_img.png"))); // NOI18N
        FOTO_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FOTO_BTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FOTO_BTNMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout FOTO_BTNLayout = new javax.swing.GroupLayout(FOTO_BTN);
        FOTO_BTN.setLayout(FOTO_BTNLayout);
        FOTO_BTNLayout.setHorizontalGroup(
            FOTO_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        FOTO_BTNLayout.setVerticalGroup(
            FOTO_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel1.add(FOTO_BTN);
        FOTO_BTN.setBounds(690, 420, 45, 45);

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Status:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(470, 380, 60, 24);

        statusvi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusvi_txtActionPerformed(evt);
            }
        });
        statusvi_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                statusvi_txtKeyPressed(evt);
            }
        });
        jPanel1.add(statusvi_txt);
        statusvi_txt.setBounds(530, 380, 125, 24);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 780, 90);

        CONSULTARVI_BTN.setBackground(new java.awt.Color(33, 63, 110));
        CONSULTARVI_BTN.setText("CONSULTAR");
        CONSULTARVI_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        CONSULTARVI_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CONSULTARVI_BTNMouseEntered(evt);
            }
        });
        CONSULTARVI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTARVI_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CONSULTARVI_BTN);
        CONSULTARVI_BTN.setBounds(70, 450, 150, 35);

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Código:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(50, 380, 60, 24);

        codvi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codvi_txtActionPerformed(evt);
            }
        });
        codvi_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codvi_txtKeyPressed(evt);
            }
        });
        jPanel1.add(codvi_txt);
        codvi_txt.setBounds(120, 380, 125, 24);

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Hora:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(290, 400, 40, 24);

        horaentradavi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaentradavi_txtActionPerformed(evt);
            }
        });
        horaentradavi_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                horaentradavi_txtKeyPressed(evt);
            }
        });
        jPanel1.add(horaentradavi_txt);
        horaentradavi_txt.setBounds(340, 400, 125, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VOLTAR_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTAR_BTNMouseClicked
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTAR_BTNMouseClicked

    private void nome_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_txtActionPerformed

    private void nome_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            empresa_txt.requestFocus();
        }
    }//GEN-LAST:event_nome_txtKeyPressed

    private void doc_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_txtActionPerformed

    private void doc_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doc_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            nome_txt.requestFocus();
        }
    }//GEN-LAST:event_doc_txtKeyPressed

    private void empresa_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresa_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresa_txtActionPerformed

    private void empresa_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empresa_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            motivo_txt.requestFocus();
        }
    }//GEN-LAST:event_empresa_txtKeyPressed

    private void motivo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motivo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motivo_txtActionPerformed

    private void motivo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motivo_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            contato_txt.requestFocus();
        }
    }//GEN-LAST:event_motivo_txtKeyPressed

    private void contato_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contato_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contato_txtActionPerformed

    private void contato_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contato_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            colaborador_txt.requestFocus();
        }
    }//GEN-LAST:event_contato_txtKeyPressed

    private void colaborador_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaborador_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colaborador_txtActionPerformed

    private void colaborador_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colaborador_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            LIMPAR_BTN.doClick();
        }
    }//GEN-LAST:event_colaborador_txtKeyPressed

    private void ALTERARVI_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALTERARVI_BTNMouseEntered
        ALTERARVI_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ALTERARVI_BTNMouseEntered

    private void ALTERARVI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTERARVI_BTNActionPerformed

    String documento = doc_txt.getText().trim();
    if (documento.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o documento do visitante!");
        return;
    }

    Visitante v = new Visitante();
    v.setNome(nome_txt.getText().trim());
    v.setDocumento(documento);
    v.setEmpresa(empresa_txt.getText().trim());
    v.setMotivo(motivo_txt.getText().trim());
    v.setContato(contato_txt.getText().trim());
    v.setColaborador(colaborador_txt.getText().trim());
    v.setStatus(statusvi_txt.getText().trim());
    v.setFoto(caminhoImagem); // ✅ salva o caminho atual ou novo

    boolean atualizado = Controller.Consultar_DAO.atualizarVisitante(v);
    if (atualizado) {
        JOptionPane.showMessageDialog(this, "Visitante atualizado com sucesso!");
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar visitante!");
    }

    }//GEN-LAST:event_ALTERARVI_BTNActionPerformed

    private void LIMPAR_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIMPAR_BTNMouseEntered
        LIMPAR_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LIMPAR_BTNMouseEntered

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        new SplashScreenMenu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    private void LIMPAR_BTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LIMPAR_BTNKeyPressed

    }//GEN-LAST:event_LIMPAR_BTNKeyPressed

    private void dataentradavi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataentradavi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataentradavi_txtActionPerformed

    private void dataentradavi_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataentradavi_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataentradavi_txtKeyPressed

    private void statusvi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusvi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusvi_txtActionPerformed

    private void statusvi_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusvi_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusvi_txtKeyPressed

    private void CONSULTARVI_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONSULTARVI_BTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CONSULTARVI_BTNMouseEntered

    private void CONSULTARVI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTARVI_BTNActionPerformed

    String doc = doc_txt.getText().trim();
    if (doc.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o documento!");
        return;
    }

    Visitante v = Consultar_DAO.consultarVisitante(doc);
    if (v != null) {
        nome_txt.setText(v.getNome());
        empresa_txt.setText(v.getEmpresa());
        motivo_txt.setText(v.getMotivo());
        contato_txt.setText(v.getContato());
        colaborador_txt.setText(v.getColaborador());
        codvi_txt.setText(String.valueOf(v.getCodigo()));
        dataentradavi_txt.setText(v.getDataEntrada());
        horaentradavi_txt.setText(v.getHoraEntrada());
        statusvi_txt.setText(v.getStatus());
        caminhoImagem = v.getFoto();

        if (v.getFoto() != null && !v.getFoto().isEmpty()) {
            ImageIcon icon = new ImageIcon(v.getFoto());
            Image img = icon.getImage().getScaledInstance(
                    foto_img.getWidth(),
                    foto_img.getHeight(),
                    Image.SCALE_SMOOTH
            );
            foto_img.setIcon(new ImageIcon(img));
        } else {
            foto_img.setIcon(null);
        }

    } else {
        JOptionPane.showMessageDialog(this, "Visitante não encontrado!");
        foto_img.setIcon(null);
        caminhoImagem = "";
    }

    }//GEN-LAST:event_CONSULTARVI_BTNActionPerformed

    private void codvi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codvi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codvi_txtActionPerformed

    private void codvi_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codvi_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_codvi_txtKeyPressed

    private void FOTO_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOTO_BTNMouseEntered
        FOTO_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_FOTO_BTNMouseEntered

    private void FOTO_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOTO_BTNMouseClicked
        JFileChooser arquivo = new JFileChooser();
    arquivo.setDialogTitle("Selecione uma imagem");
    arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);

    int retorno = arquivo.showOpenDialog(this);
    if (retorno == JFileChooser.APPROVE_OPTION) {
        File file = arquivo.getSelectedFile();
        caminhoImagem = file.getAbsolutePath(); // ✅ guarda o caminho

        try {
            ImageIcon icon = new ImageIcon(caminhoImagem);
            Image imgEscalada = icon.getImage().getScaledInstance(
                    foto_img.getWidth(),
                    foto_img.getHeight(),
                    Image.SCALE_SMOOTH
            );
            foto_img.setIcon(new ImageIcon(imgEscalada));
            foto_img.repaint();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar imagem: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Nenhuma imagem selecionada.");
    }
    }//GEN-LAST:event_FOTO_BTNMouseClicked

    private void horaentradavi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaentradavi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaentradavi_txtActionPerformed

    private void horaentradavi_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horaentradavi_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaentradavi_txtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaATTVI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaATTVI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaATTVI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaATTVI_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaATTVI_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound ALTERARVI_BTN;
    private org.edisoncor.gui.button.ButtonRound CONSULTARVI_BTN;
    private org.edisoncor.gui.panel.PanelImage FOTO_BTN;
    private org.edisoncor.gui.button.ButtonRound LIMPAR_BTN;
    private org.edisoncor.gui.panel.PanelImage VOLTAR_BTN;
    private org.edisoncor.gui.textField.TextFieldRound codvi_txt;
    private org.edisoncor.gui.textField.TextFieldRound colaborador_txt;
    private org.edisoncor.gui.textField.TextFieldRound contato_txt;
    private org.edisoncor.gui.textField.TextFieldRound dataentradavi_txt;
    private org.edisoncor.gui.textField.TextFieldRound doc_txt;
    private org.edisoncor.gui.textField.TextFieldRound empresa_txt;
    private javax.persistence.EntityManager entityManager;
    private org.edisoncor.gui.panel.PanelImage foto_img;
    private org.edisoncor.gui.textField.TextFieldRound horaentradavi_txt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.textField.TextFieldRound motivo_txt;
    private org.edisoncor.gui.textField.TextFieldRound nome_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.textField.TextFieldRound statusvi_txt;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
