/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Usuario_DAO;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CriarUsuario_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CriarUsuario_GUI
     */
    public CriarUsuario_GUI() {
        initComponents();
        nome_txt.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        VOLTAR_BTN = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel6 = new javax.swing.JLabel();
        usuario_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel8 = new javax.swing.JLabel();
        senha_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel9 = new javax.swing.JLabel();
        tipo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        CANCELAR_BTN = new org.edisoncor.gui.button.ButtonRound();
        CRIAR_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nome_txt = new org.edisoncor.gui.textField.TextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 74), 4, true));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("C R I A R");

        VOLTAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/voltar_img.png"))); // NOI18N
        VOLTAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLTAR_BTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VOLTAR_BTNLayout = new javax.swing.GroupLayout(VOLTAR_BTN);
        VOLTAR_BTN.setLayout(VOLTAR_BTNLayout);
        VOLTAR_BTNLayout.setHorizontalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        VOLTAR_BTNLayout.setVerticalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(4, 4, 792, 80);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.rodape_img.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(4, 496, 792, 100);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Usuário:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 330, 60, 24);

        usuario_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_txtActionPerformed(evt);
            }
        });
        usuario_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuario_txtKeyPressed(evt);
            }
        });
        jPanel1.add(usuario_txt);
        usuario_txt.setBounds(130, 330, 125, 24);

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tipo:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 330, 40, 24);

        senha_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_txtActionPerformed(evt);
            }
        });
        senha_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senha_txtKeyPressed(evt);
            }
        });
        jPanel1.add(senha_txt);
        senha_txt.setBounds(360, 330, 125, 24);

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Senha:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(290, 330, 50, 24);

        tipo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_txtActionPerformed(evt);
            }
        });
        tipo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(tipo_txt);
        tipo_txt.setBounds(580, 330, 125, 24);

        CANCELAR_BTN.setBackground(new java.awt.Color(33, 63, 110));
        CANCELAR_BTN.setText("CANCELAR");
        CANCELAR_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        CANCELAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CANCELAR_BTNMouseEntered(evt);
            }
        });
        CANCELAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CANCELAR_BTN);
        CANCELAR_BTN.setBounds(160, 430, 150, 35);

        CRIAR_BTN.setBackground(new java.awt.Color(33, 63, 110));
        CRIAR_BTN.setText("CRIAR");
        CRIAR_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        CRIAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CRIAR_BTNMouseEntered(evt);
            }
        });
        CRIAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRIAR_BTNActionPerformed(evt);
            }
        });
        CRIAR_BTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CRIAR_BTNKeyPressed(evt);
            }
        });
        jPanel1.add(CRIAR_BTN);
        CRIAR_BTN.setBounds(490, 430, 150, 35);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("USUÁRIO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 160, 118, 24);

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nome:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(290, 250, 50, 24);

        nome_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_txtActionPerformed(evt);
            }
        });
        nome_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nome_txtKeyPressed(evt);
            }
        });
        jPanel1.add(nome_txt);
        nome_txt.setBounds(360, 250, 125, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VOLTAR_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTAR_BTNMouseClicked
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTAR_BTNMouseClicked

    private void usuario_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_txtActionPerformed

    private void usuario_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuario_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            senha_txt.requestFocus();
        }
    }//GEN-LAST:event_usuario_txtKeyPressed

    private void senha_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha_txtActionPerformed

    private void senha_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senha_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            tipo_txt.requestFocus();
        }
    }//GEN-LAST:event_senha_txtKeyPressed

    private void tipo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_txtActionPerformed

    private void tipo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipo_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            CRIAR_BTN.doClick();
        }
    }//GEN-LAST:event_tipo_txtKeyPressed

    private void CANCELAR_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELAR_BTNMouseEntered
        CANCELAR_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CANCELAR_BTNMouseEntered

    private void CANCELAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELAR_BTNActionPerformed
        nome_txt.setText("");
        usuario_txt.setText("");
        senha_txt.setText("");
        tipo_txt.setText("");
    }//GEN-LAST:event_CANCELAR_BTNActionPerformed

    private void CRIAR_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CRIAR_BTNMouseEntered
        CRIAR_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CRIAR_BTNMouseEntered

    private void CRIAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRIAR_BTNActionPerformed
        String nome = nome_txt.getText().trim();
    String usuario = usuario_txt.getText().trim();
    String senha = senha_txt.getText().trim();
    String tipo = tipo_txt.getText().trim(); // pode ser JComboBox também

    // Validação básica
    if (nome.isEmpty() || usuario.isEmpty() || senha.isEmpty() || tipo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Cria objeto do modelo
    Usuario novo = new Usuario();
    novo.setNome(nome);
    novo.setUsuario(usuario);
    novo.setSenha(senha);
    novo.setTipo(tipo);

    // Chama o DAO
    Usuario_DAO dao = new Usuario_DAO();
    boolean sucesso = dao.inserir(novo);

    if (sucesso) {
        JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");
        nome_txt.setText("");
        usuario_txt.setText("");
        senha_txt.setText("");
        tipo_txt.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_CRIAR_BTNActionPerformed

    private void CRIAR_BTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CRIAR_BTNKeyPressed

    }//GEN-LAST:event_CRIAR_BTNKeyPressed

    private void nome_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_txtActionPerformed

    private void nome_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            usuario_txt.requestFocus();
        }
    }//GEN-LAST:event_nome_txtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarUsuario_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarUsuario_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarUsuario_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarUsuario_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarUsuario_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound CANCELAR_BTN;
    private org.edisoncor.gui.button.ButtonRound CRIAR_BTN;
    private org.edisoncor.gui.panel.PanelImage VOLTAR_BTN;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.textField.TextFieldRound nome_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.textField.TextFieldRound senha_txt;
    private org.edisoncor.gui.textField.TextFieldRound tipo_txt;
    private org.edisoncor.gui.textField.TextFieldRound usuario_txt;
    // End of variables declaration//GEN-END:variables
}
