/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Entrada_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Entrada_GUI
     */
    public Entrada_GUI() {
        initComponents();
        colaborador_txt.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        VOLTAR_BTN = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel6 = new javax.swing.JLabel();
        placa_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel7 = new javax.swing.JLabel();
        modelo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        categoria_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel10 = new javax.swing.JLabel();
        CANCELAR_BTN = new org.edisoncor.gui.button.ButtonRound();
        ENTRADA_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nome_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel19 = new javax.swing.JLabel();
        doc_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel20 = new javax.swing.JLabel();
        motivo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel9 = new javax.swing.JLabel();
        vaga_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel12 = new javax.swing.JLabel();
        plano_txt = new org.edisoncor.gui.textField.TextFieldRound();
        BUSCARINFO_BTN = new org.edisoncor.gui.panel.PanelImage();
        jLabel13 = new javax.swing.JLabel();
        colaborador_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel15 = new javax.swing.JLabel();
        dataentradave_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel23 = new javax.swing.JLabel();
        horaentradavei_txt = new org.edisoncor.gui.textField.TextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 74), 4, true));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("E N T R A D A");

        VOLTAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/voltar_img.png"))); // NOI18N
        VOLTAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLTAR_BTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VOLTAR_BTNLayout = new javax.swing.GroupLayout(VOLTAR_BTN);
        VOLTAR_BTN.setLayout(VOLTAR_BTNLayout);
        VOLTAR_BTNLayout.setHorizontalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        VOLTAR_BTNLayout.setVerticalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(4, 4, 792, 80);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.rodape_img.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(4, 496, 792, 100);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("*Placa:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 270, 50, 24);

        placa_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa_txtActionPerformed(evt);
            }
        });
        placa_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                placa_txtKeyPressed(evt);
            }
        });
        jPanel1.add(placa_txt);
        placa_txt.setBounds(110, 270, 125, 24);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Modelo:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 270, 60, 24);

        modelo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelo_txtActionPerformed(evt);
            }
        });
        modelo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modelo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(modelo_txt);
        modelo_txt.setBounds(330, 270, 125, 24);

        categoria_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoria_txtActionPerformed(evt);
            }
        });
        categoria_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                categoria_txtKeyPressed(evt);
            }
        });
        jPanel1.add(categoria_txt);
        categoria_txt.setBounds(560, 270, 125, 24);

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Categoria:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(470, 270, 71, 24);

        CANCELAR_BTN.setBackground(new java.awt.Color(33, 63, 110));
        CANCELAR_BTN.setText("CANCELAR");
        CANCELAR_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        CANCELAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CANCELAR_BTNMouseEntered(evt);
            }
        });
        CANCELAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CANCELAR_BTN);
        CANCELAR_BTN.setBounds(150, 440, 150, 35);

        ENTRADA_BTN.setBackground(new java.awt.Color(33, 63, 110));
        ENTRADA_BTN.setText("ENTRADA");
        ENTRADA_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ENTRADA_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ENTRADA_BTNMouseEntered(evt);
            }
        });
        ENTRADA_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTRADA_BTNActionPerformed(evt);
            }
        });
        ENTRADA_BTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ENTRADA_BTNKeyPressed(evt);
            }
        });
        jPanel1.add(ENTRADA_BTN);
        ENTRADA_BTN.setBounds(480, 440, 150, 35);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENTRADA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 330, 104, 24);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VEÍCULO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 220, 97, 24);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("VISITANTE");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(320, 110, 170, 24);

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nome:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(270, 160, 50, 24);

        nome_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_txtActionPerformed(evt);
            }
        });
        nome_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nome_txtKeyPressed(evt);
            }
        });
        jPanel1.add(nome_txt);
        nome_txt.setBounds(330, 160, 125, 24);

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("*RG/CPF:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(40, 160, 65, 24);

        doc_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_txtActionPerformed(evt);
            }
        });
        doc_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                doc_txtKeyPressed(evt);
            }
        });
        jPanel1.add(doc_txt);
        doc_txt.setBounds(110, 160, 125, 24);

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Motivo:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(480, 160, 60, 24);

        motivo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motivo_txtActionPerformed(evt);
            }
        });
        motivo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                motivo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(motivo_txt);
        motivo_txt.setBounds(560, 160, 125, 24);

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Vaga:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 380, 40, 24);

        vaga_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga_txtActionPerformed(evt);
            }
        });
        vaga_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vaga_txtKeyPressed(evt);
            }
        });
        jPanel1.add(vaga_txt);
        vaga_txt.setBounds(350, 380, 125, 24);

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Plano:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(530, 380, 60, 24);

        plano_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plano_txtActionPerformed(evt);
            }
        });
        plano_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                plano_txtKeyPressed(evt);
            }
        });
        jPanel1.add(plano_txt);
        plano_txt.setBounds(600, 380, 125, 24);

        BUSCARINFO_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscarinfo_img.png"))); // NOI18N
        BUSCARINFO_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BUSCARINFO_BTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BUSCARINFO_BTNMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout BUSCARINFO_BTNLayout = new javax.swing.GroupLayout(BUSCARINFO_BTN);
        BUSCARINFO_BTN.setLayout(BUSCARINFO_BTNLayout);
        BUSCARINFO_BTNLayout.setHorizontalGroup(
            BUSCARINFO_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        BUSCARINFO_BTNLayout.setVerticalGroup(
            BUSCARINFO_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(BUSCARINFO_BTN);
        BUSCARINFO_BTN.setBounds(710, 200, 50, 50);

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Colaborador:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 100, 90, 24);

        colaborador_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaborador_txtActionPerformed(evt);
            }
        });
        colaborador_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                colaborador_txtKeyPressed(evt);
            }
        });
        jPanel1.add(colaborador_txt);
        colaborador_txt.setBounds(110, 100, 125, 24);

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Data:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(60, 360, 40, 24);

        dataentradave_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataentradave_txtActionPerformed(evt);
            }
        });
        dataentradave_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dataentradave_txtKeyPressed(evt);
            }
        });
        jPanel1.add(dataentradave_txt);
        dataentradave_txt.setBounds(110, 360, 125, 24);

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Hora:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(60, 400, 40, 24);

        horaentradavei_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaentradavei_txtActionPerformed(evt);
            }
        });
        horaentradavei_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                horaentradavei_txtKeyPressed(evt);
            }
        });
        jPanel1.add(horaentradavei_txt);
        horaentradavei_txt.setBounds(110, 400, 125, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VOLTAR_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTAR_BTNMouseClicked
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTAR_BTNMouseClicked

    private void placa_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placa_txtActionPerformed

    private void placa_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placa_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            modelo_txt.requestFocus();
        }
    }//GEN-LAST:event_placa_txtKeyPressed

    private void modelo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelo_txtActionPerformed

    private void modelo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelo_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            categoria_txt.requestFocus();
        }
    }//GEN-LAST:event_modelo_txtKeyPressed

    private void categoria_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoria_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria_txtActionPerformed

    private void categoria_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoria_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            vaga_txt.requestFocus();
        }
    }//GEN-LAST:event_categoria_txtKeyPressed

    private void CANCELAR_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELAR_BTNMouseEntered
        CANCELAR_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CANCELAR_BTNMouseEntered

    private void CANCELAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELAR_BTNActionPerformed
        placa_txt.setText("");
        modelo_txt.setText("");
        categoria_txt.setText("");
        nome_txt.setText("");
        doc_txt.setText("");
        motivo_txt.setText("");
        dataentradavei_txt.setText("");
        vaga_txt.setText("");
        plano_txt.setText("");
        colaborador_txt.setText("");
    }//GEN-LAST:event_CANCELAR_BTNActionPerformed

    private void ENTRADA_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENTRADA_BTNMouseEntered
        ENTRADA_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ENTRADA_BTNMouseEntered

    private void ENTRADA_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTRADA_BTNActionPerformed
        String documento = doc_txt.getText().trim();
    String nome = nome_txt.getText().trim();
    String motivo = motivo_txt.getText().trim();
    String placa = placa_txt.getText().trim();
    String modelo = modelo_txt.getText().trim();
    String categoria = categoria_txt.getText().trim();
    String colaborador = colaborador_txt.getText().trim();
    String vaga = vaga_txt.getText().trim();
    String plano = plano_txt.getText().trim();

    if (documento.isEmpty() || placa.isEmpty() || colaborador.isEmpty() || vaga.isEmpty() || plano.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios!");
        return;
    }

    boolean sucesso = Controller.Entrada_DAO.registrarEntrada(
        documento, nome, motivo, placa, modelo, categoria, colaborador, vaga, plano
    );

    if (sucesso) {
        JOptionPane.showMessageDialog(this, "Entrada registrada com sucesso!");
        doc_txt.setText("");
        nome_txt.setText("");
        motivo_txt.setText("");
        placa_txt.setText("");
        modelo_txt.setText("");
        categoria_txt.setText("");
        colaborador_txt.setText("");
        vaga_txt.setText("");
        plano_txt.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao registrar entrada!");
    }
    }//GEN-LAST:event_ENTRADA_BTNActionPerformed

    private void ENTRADA_BTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ENTRADA_BTNKeyPressed

    }//GEN-LAST:event_ENTRADA_BTNKeyPressed

    private void nome_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_txtActionPerformed

    private void nome_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            motivo_txt.requestFocus();
        }
    }//GEN-LAST:event_nome_txtKeyPressed

    private void doc_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_txtActionPerformed

    private void doc_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doc_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            nome_txt.requestFocus();
        }
    }//GEN-LAST:event_doc_txtKeyPressed

    private void motivo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motivo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motivo_txtActionPerformed

    private void motivo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motivo_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            placa_txt.requestFocus();
        }
    }//GEN-LAST:event_motivo_txtKeyPressed

    private void vaga_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga_txtActionPerformed

    private void vaga_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vaga_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            plano_txt.requestFocus();
        }
    }//GEN-LAST:event_vaga_txtKeyPressed

    private void plano_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plano_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plano_txtActionPerformed

    private void plano_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plano_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            ENTRADA_BTN.doClick();
        }
    }//GEN-LAST:event_plano_txtKeyPressed

    private void colaborador_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaborador_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colaborador_txtActionPerformed

    private void colaborador_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colaborador_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            doc_txt.requestFocus();
        }
    }//GEN-LAST:event_colaborador_txtKeyPressed

    private void dataentradave_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataentradave_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataentradave_txtActionPerformed

    private void dataentradave_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataentradave_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataentradave_txtKeyPressed

    private void horaentradavei_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaentradavei_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaentradavei_txtActionPerformed

    private void horaentradavei_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horaentradavei_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaentradavei_txtKeyPressed

    private void BUSCARINFO_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUSCARINFO_BTNMouseClicked
        String documento = doc_txt.getText().trim();
    String placa = placa_txt.getText().trim();

    if (!documento.isEmpty()) {
        String[] visitante = Controller.Entrada_DAO.buscarVisitante(documento);
        if (visitante != null) {
            nome_txt.setText(visitante[0]);
            motivo_txt.setText(visitante[1]);
        } else {
            JOptionPane.showMessageDialog(this, "Visitante não encontrado!");
        }
    }

    if (!placa.isEmpty()) {
        String[] veiculo = Controller.Entrada_DAO.buscarVeiculo(placa);
        if (veiculo != null) {
            modelo_txt.setText(veiculo[0]);
            categoria_txt.setText(veiculo[1]);
        } else {
            JOptionPane.showMessageDialog(this, "Veículo não encontrado!");
        }
    }
    }//GEN-LAST:event_BUSCARINFO_BTNMouseClicked

    private void BUSCARINFO_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUSCARINFO_BTNMouseEntered
        BUSCARINFO_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BUSCARINFO_BTNMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage BUSCARINFO_BTN;
    private org.edisoncor.gui.button.ButtonRound CANCELAR_BTN;
    private org.edisoncor.gui.button.ButtonRound ENTRADA_BTN;
    private org.edisoncor.gui.panel.PanelImage VOLTAR_BTN;
    private org.edisoncor.gui.textField.TextFieldRound categoria_txt;
    private org.edisoncor.gui.textField.TextFieldRound colaborador_txt;
    private org.edisoncor.gui.textField.TextFieldRound dataentradave_txt;
    private org.edisoncor.gui.textField.TextFieldRound dataentradavei_txt;
    private org.edisoncor.gui.textField.TextFieldRound doc_txt;
    private org.edisoncor.gui.textField.TextFieldRound horaentradavei_txt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.textField.TextFieldRound modelo_txt;
    private org.edisoncor.gui.textField.TextFieldRound motivo_txt;
    private org.edisoncor.gui.textField.TextFieldRound nome_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.textField.TextFieldRound placa_txt;
    private org.edisoncor.gui.textField.TextFieldRound plano_txt;
    private org.edisoncor.gui.textField.TextFieldRound vaga_txt;
    // End of variables declaration//GEN-END:variables
}
