/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Usuario_Controller;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class GerenciarUsuario_GUI extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarUsuario_GUI
     */
    public GerenciarUsuario_GUI() {
        initComponents();
        nome_txt.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("tech_solutions?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        VOLTAR_BTN = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        ALTERARVI_BTN = new org.edisoncor.gui.button.ButtonRound();
        EXCLUIR_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        CONSULTARVI_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel10 = new javax.swing.JLabel();
        nome_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel9 = new javax.swing.JLabel();
        senha_txt = new org.edisoncor.gui.textField.TextFieldRound();
        usuario_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tipo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        LIMPAR_BTN1 = new org.edisoncor.gui.button.ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 74), 4, true));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("G E R E N C I A R");

        VOLTAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/voltar_img.png"))); // NOI18N
        VOLTAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLTAR_BTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VOLTAR_BTNLayout = new javax.swing.GroupLayout(VOLTAR_BTN);
        VOLTAR_BTN.setLayout(VOLTAR_BTNLayout);
        VOLTAR_BTNLayout.setHorizontalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        VOLTAR_BTNLayout.setVerticalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(4, 4, 792, 80);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.rodape_img.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(4, 496, 792, 100);

        ALTERARVI_BTN.setBackground(new java.awt.Color(33, 63, 110));
        ALTERARVI_BTN.setText("ALTERAR");
        ALTERARVI_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ALTERARVI_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ALTERARVI_BTNMouseEntered(evt);
            }
        });
        ALTERARVI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTERARVI_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(ALTERARVI_BTN);
        ALTERARVI_BTN.setBounds(220, 430, 150, 35);

        EXCLUIR_BTN.setBackground(new java.awt.Color(33, 63, 110));
        EXCLUIR_BTN.setText("EXCLUIR");
        EXCLUIR_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        EXCLUIR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EXCLUIR_BTNMouseEntered(evt);
            }
        });
        EXCLUIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_BTNActionPerformed(evt);
            }
        });
        EXCLUIR_BTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EXCLUIR_BTNKeyPressed(evt);
            }
        });
        jPanel1.add(EXCLUIR_BTN);
        EXCLUIR_BTN.setBounds(440, 430, 150, 35);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuário");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 110, 83, 24);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 780, 90);

        CONSULTARVI_BTN.setBackground(new java.awt.Color(33, 63, 110));
        CONSULTARVI_BTN.setText("CONSULTAR");
        CONSULTARVI_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        CONSULTARVI_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CONSULTARVI_BTNMouseEntered(evt);
            }
        });
        CONSULTARVI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTARVI_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CONSULTARVI_BTN);
        CONSULTARVI_BTN.setBounds(40, 430, 150, 35);

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nome:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(200, 320, 50, 24);

        nome_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_txtActionPerformed(evt);
            }
        });
        nome_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nome_txtKeyPressed(evt);
            }
        });
        jPanel1.add(nome_txt);
        nome_txt.setBounds(260, 320, 125, 24);

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Senha:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 380, 50, 24);

        senha_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_txtActionPerformed(evt);
            }
        });
        senha_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senha_txtKeyPressed(evt);
            }
        });
        jPanel1.add(senha_txt);
        senha_txt.setBounds(260, 380, 125, 24);

        usuario_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_txtActionPerformed(evt);
            }
        });
        usuario_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuario_txtKeyPressed(evt);
            }
        });
        jPanel1.add(usuario_txt);
        usuario_txt.setBounds(460, 320, 125, 24);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Usuário:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 320, 60, 24);

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tipo:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(410, 380, 40, 24);

        tipo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_txtActionPerformed(evt);
            }
        });
        tipo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(tipo_txt);
        tipo_txt.setBounds(460, 380, 125, 24);

        LIMPAR_BTN1.setBackground(new java.awt.Color(33, 63, 110));
        LIMPAR_BTN1.setText("LIMPAR");
        LIMPAR_BTN1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        LIMPAR_BTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LIMPAR_BTN1MouseEntered(evt);
            }
        });
        LIMPAR_BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTN1ActionPerformed(evt);
            }
        });
        LIMPAR_BTN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LIMPAR_BTN1KeyPressed(evt);
            }
        });
        jPanel1.add(LIMPAR_BTN1);
        LIMPAR_BTN1.setBounds(620, 430, 150, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VOLTAR_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTAR_BTNMouseClicked
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTAR_BTNMouseClicked

    private void ALTERARVI_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALTERARVI_BTNMouseEntered
        ALTERARVI_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ALTERARVI_BTNMouseEntered

    private void ALTERARVI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTERARVI_BTNActionPerformed
        Usuario_Controller controller = new Usuario_Controller();
        if (controller.atualizarUsuario(nome_txt.getText(), usuario_txt.getText(), senha_txt.getText(), tipo_txt.getText())) {
        JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!");
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar usuário!");
    }
    }//GEN-LAST:event_ALTERARVI_BTNActionPerformed

    private void EXCLUIR_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXCLUIR_BTNMouseEntered
        EXCLUIR_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_EXCLUIR_BTNMouseEntered

    private void EXCLUIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_BTNActionPerformed
        Usuario_Controller controller = new Usuario_Controller();
        int confirm = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este usuário?");
    if (confirm == JOptionPane.YES_OPTION) {
        if (controller.excluirUsuario(usuario_txt.getText())) {
            JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir usuário!");
        }
    }
    }//GEN-LAST:event_EXCLUIR_BTNActionPerformed

    private void EXCLUIR_BTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EXCLUIR_BTNKeyPressed

    }//GEN-LAST:event_EXCLUIR_BTNKeyPressed

    private void CONSULTARVI_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONSULTARVI_BTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CONSULTARVI_BTNMouseEntered

    private void CONSULTARVI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTARVI_BTNActionPerformed
        Usuario_Controller controller = new Usuario_Controller();
        Usuario u = controller.consultarUsuario(usuario_txt.getText());

        if (u != null) {
            nome_txt.setText(u.getNome());
            senha_txt.setText(u.getSenha());
            tipo_txt.setText(u.getTipo());
        } else {
            JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
        }
    }//GEN-LAST:event_CONSULTARVI_BTNActionPerformed

    private void nome_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_txtActionPerformed

    private void nome_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            usuario_txt.requestFocus();
        }
    }//GEN-LAST:event_nome_txtKeyPressed

    private void senha_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha_txtActionPerformed

    private void senha_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senha_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            tipo_txt.requestFocus();
        }
    }//GEN-LAST:event_senha_txtKeyPressed

    private void usuario_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_txtActionPerformed

    private void usuario_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuario_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            senha_txt.requestFocus();
        }
    }//GEN-LAST:event_usuario_txtKeyPressed

    private void tipo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_txtActionPerformed

    private void tipo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipo_txtKeyPressed

    }//GEN-LAST:event_tipo_txtKeyPressed

    private void LIMPAR_BTN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIMPAR_BTN1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LIMPAR_BTN1MouseEntered

    private void LIMPAR_BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LIMPAR_BTN1ActionPerformed

    private void LIMPAR_BTN1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LIMPAR_BTN1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LIMPAR_BTN1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarUsuario_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound ALTERARVI_BTN;
    private org.edisoncor.gui.button.ButtonRound CONSULTARVI_BTN;
    private org.edisoncor.gui.button.ButtonRound EXCLUIR_BTN;
    private org.edisoncor.gui.button.ButtonRound LIMPAR_BTN1;
    private org.edisoncor.gui.panel.PanelImage VOLTAR_BTN;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.textField.TextFieldRound nome_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.textField.TextFieldRound senha_txt;
    private javax.swing.JTable tabela;
    private org.edisoncor.gui.textField.TextFieldRound tipo_txt;
    private org.edisoncor.gui.textField.TextFieldRound usuario_txt;
    // End of variables declaration//GEN-END:variables
}
