/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        barraTitle1 = new org.edisoncor.gui.varios.BarraTitle();
        jLabel1 = new javax.swing.JLabel();
        chrome_img = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        notepad_img = new org.edisoncor.gui.panel.PanelImage();
        jLabel3 = new javax.swing.JLabel();
        calc_img = new org.edisoncor.gui.panel.PanelImage();
        jLabel4 = new javax.swing.JLabel();
        lixeira_img = new org.edisoncor.gui.panel.PanelImage();
        aplicativo_img = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelImage1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.fundo_img.jpg"))); // NOI18N
        panelImage1.setLayout(null);
        panelImage1.add(barraTitle1);
        barraTitle1.setBounds(4, 4, 792, 30);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        panelImage1.add(jLabel1);
        jLabel1.setBounds(103, 457, 0, 0);

        chrome_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chrome_img.png"))); // NOI18N
        chrome_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chrome_imgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chrome_imgMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout chrome_imgLayout = new javax.swing.GroupLayout(chrome_img);
        chrome_img.setLayout(chrome_imgLayout);
        chrome_imgLayout.setHorizontalGroup(
            chrome_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        chrome_imgLayout.setVerticalGroup(
            chrome_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelImage1.add(chrome_img);
        chrome_img.setBounds(695, 66, 76, 75);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        panelImage1.add(jLabel2);
        jLabel2.setBounds(705, 148, 0, 0);

        notepad_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/notepad_img.png"))); // NOI18N
        notepad_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notepad_imgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                notepad_imgMouseEntered(evt);
            }
        });
        notepad_img.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                notepad_imgKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout notepad_imgLayout = new javax.swing.GroupLayout(notepad_img);
        notepad_img.setLayout(notepad_imgLayout);
        notepad_imgLayout.setHorizontalGroup(
            notepad_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        notepad_imgLayout.setVerticalGroup(
            notepad_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelImage1.add(notepad_img);
        notepad_img.setBounds(28, 172, 75, 75);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        panelImage1.add(jLabel3);
        jLabel3.setBounds(181, 154, 0, 0);

        calc_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/calculadora_img.png"))); // NOI18N
        calc_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calc_imgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calc_imgMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout calc_imgLayout = new javax.swing.GroupLayout(calc_img);
        calc_img.setLayout(calc_imgLayout);
        calc_imgLayout.setHorizontalGroup(
            calc_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        calc_imgLayout.setVerticalGroup(
            calc_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelImage1.add(calc_img);
        calc_img.setBounds(700, 160, 75, 75);

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        panelImage1.add(jLabel4);
        jLabel4.setBounds(784, 457, 0, 0);

        lixeira_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lixeira_img.png"))); // NOI18N
        lixeira_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lixeira_imgMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout lixeira_imgLayout = new javax.swing.GroupLayout(lixeira_img);
        lixeira_img.setLayout(lixeira_imgLayout);
        lixeira_imgLayout.setHorizontalGroup(
            lixeira_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        lixeira_imgLayout.setVerticalGroup(
            lixeira_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelImage1.add(lixeira_img);
        lixeira_img.setBounds(28, 66, 75, 75);

        aplicativo_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.rem.app_img.png"))); // NOI18N
        aplicativo_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aplicativo_imgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aplicativo_imgMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout aplicativo_imgLayout = new javax.swing.GroupLayout(aplicativo_img);
        aplicativo_img.setLayout(aplicativo_imgLayout);
        aplicativo_imgLayout.setHorizontalGroup(
            aplicativo_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        aplicativo_imgLayout.setVerticalGroup(
            aplicativo_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        panelImage1.add(aplicativo_img);
        aplicativo_img.setBounds(323, 78, 150, 115);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/windows_img.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelImage1.add(panelImage2);
        panelImage2.setBounds(30, 530, 50, 50);

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pesquisa_img.png"))); // NOI18N

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        panelImage1.add(panelImage3);
        panelImage3.setBounds(100, 510, 130, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chrome_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chrome_imgMouseClicked
        try {
            Runtime.getRuntime().exec("cmd /c start chrome https://www.google.com") ;
        } catch (IOException ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_chrome_imgMouseClicked

    private void calc_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calc_imgMouseEntered
        calc_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_calc_imgMouseEntered

    private void calc_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calc_imgMouseClicked
        try {
            Runtime.getRuntime().exec("cmd /c start calc") ;
        } catch (IOException ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_calc_imgMouseClicked

    private void notepad_imgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_notepad_imgKeyPressed
        
    }//GEN-LAST:event_notepad_imgKeyPressed

    private void aplicativo_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aplicativo_imgMouseClicked
        new SplashScreenLogin_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_aplicativo_imgMouseClicked

    private void notepad_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notepad_imgMouseClicked
        try {
            Runtime.getRuntime().exec("cmd /c start notepad");
        }catch (IOException ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_notepad_imgMouseClicked

    private void aplicativo_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aplicativo_imgMouseEntered
        aplicativo_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_aplicativo_imgMouseEntered

    private void lixeira_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lixeira_imgMouseEntered
        lixeira_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lixeira_imgMouseEntered

    private void chrome_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chrome_imgMouseEntered
        chrome_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_chrome_imgMouseEntered

    private void notepad_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notepad_imgMouseEntered
        notepad_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_notepad_imgMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage aplicativo_img;
    private org.edisoncor.gui.varios.BarraTitle barraTitle1;
    private org.edisoncor.gui.panel.PanelImage calc_img;
    private org.edisoncor.gui.panel.PanelImage chrome_img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.edisoncor.gui.panel.PanelImage lixeira_img;
    private org.edisoncor.gui.panel.PanelImage notepad_img;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    // End of variables declaration//GEN-END:variables
}
