/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author User
 */
public class Menu_GUI extends javax.swing.JFrame {
    public static String tipoUsuarioLogado;
    public static String usuarioLogado;
    
    
    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
        mostrarInformacoes(); // chama o método pra exibir os dados
        iniciarRelogio();
        
        // Esconde menus se não for admin
        if (tipoUsuarioLogado != null && !tipoUsuarioLogado.equalsIgnoreCase("ADMIN")) {
            usuarios_menu.setVisible(false);
            relatorios_menu.setVisible(false);
            excluir_menu.setVisible(false);
        }
    } // ✅ fecha o construtor aqui!
    
        private void mostrarInformacoes() {
        if (usuarioLogado != null)
            usuario_lbl.setText("Usuário: " + usuarioLogado);
        else
            usuario_lbl.setText("Usuário: desconhecido");

        if (tipoUsuarioLogado != null)
            cargo_lbl.setText("Tipo: " + tipoUsuarioLogado);

        java.time.LocalDate data = java.time.LocalDate.now();
        data_lbl.setText("Data: " + data.toString());

        java.time.LocalTime hora = java.time.LocalTime.now().withNano(0);
        hora_lbl.setText("Hora: " + hora.toString());
    }

    private void iniciarRelogio() {
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.time.LocalTime hora = java.time.LocalTime.now().withNano(0);
            hora_lbl.setText("Hora: " + hora.toString());
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        labelCustom1 = new org.edisoncor.gui.label.LabelCustom();
        usuario_lbl = new javax.swing.JLabel();
        cargo_lbl = new javax.swing.JLabel();
        hora_lbl = new javax.swing.JLabel();
        data_lbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastro_menu = new javax.swing.JMenu();
        CADASTROVI_BTN = new javax.swing.JMenuItem();
        CADASTROVEI_BTN = new javax.swing.JMenuItem();
        consulta_menu = new javax.swing.JMenu();
        CONSULTAVI_BTN = new javax.swing.JMenuItem();
        CONSULTAVEI_BTN = new javax.swing.JMenuItem();
        excluir_menu = new javax.swing.JMenu();
        EXCLUIVI_BTN = new javax.swing.JMenuItem();
        EXLCUIVEI_BTN = new javax.swing.JMenuItem();
        controle_menu = new javax.swing.JMenu();
        ENTRADAS_BTN = new javax.swing.JMenuItem();
        SAIDAS_BTN = new javax.swing.JMenuItem();
        ESTACIONAMENTO_BTN = new javax.swing.JMenuItem();
        relatorios_menu = new javax.swing.JMenu();
        RELATORIOCLI_BTN = new javax.swing.JMenuItem();
        RELATORIOESTAC_BTN = new javax.swing.JMenuItem();
        RELATORIOFINAN_BTN = new javax.swing.JMenuItem();
        RELATORIOFUNC_BTN = new javax.swing.JMenuItem();
        usuarios_menu = new javax.swing.JMenu();
        CRIAR_BTN = new javax.swing.JMenuItem();
        GERENCIAR_BTN = new javax.swing.JMenuItem();
        PERMISSOES_BTN = new javax.swing.JMenuItem();
        conf_menu = new javax.swing.JMenu();
        TEMA_BTN = new javax.swing.JMenuItem();
        DADOS_BTN = new javax.swing.JMenuItem();
        SISTEMA_BTN = new javax.swing.JMenuItem();
        TROCAR_BTN = new javax.swing.JMenuItem();
        SAIR_BTN = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelImage1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 63, 110), 4, true));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo_img.jpg"))); // NOI18N
        panelImage1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelImage1KeyPressed(evt);
            }
        });

        labelCustom1.setBackground(new java.awt.Color(33, 63, 110));
        labelCustom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCustom1.setText("M E N U");
        labelCustom1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N

        usuario_lbl.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        usuario_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        cargo_lbl.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cargo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        hora_lbl.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        hora_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        data_lbl.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        data_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuario_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(data_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cargo_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(hora_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(labelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(labelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuario_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargo_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 110), 3));

        cadastro_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 110)));
        cadastro_menu.setText("CADASTRO");
        cadastro_menu.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        CADASTROVI_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CADASTROVI_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        CADASTROVI_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cadastro_img.png"))); // NOI18N
        CADASTROVI_BTN.setText("VISITANTE");
        CADASTROVI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTROVI_BTNActionPerformed(evt);
            }
        });
        cadastro_menu.add(CADASTROVI_BTN);

        CADASTROVEI_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        CADASTROVEI_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        CADASTROVEI_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cadastro_img.png"))); // NOI18N
        CADASTROVEI_BTN.setText("VEÍCULO");
        CADASTROVEI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTROVEI_BTNActionPerformed(evt);
            }
        });
        cadastro_menu.add(CADASTROVEI_BTN);

        jMenuBar1.add(cadastro_menu);

        consulta_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 110)));
        consulta_menu.setText("CONSULTA / ATT");
        consulta_menu.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        CONSULTAVI_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        CONSULTAVI_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        CONSULTAVI_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/consulta.att_img.png"))); // NOI18N
        CONSULTAVI_BTN.setText("VISITANTES");
        CONSULTAVI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAVI_BTNActionPerformed(evt);
            }
        });
        consulta_menu.add(CONSULTAVI_BTN);

        CONSULTAVEI_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        CONSULTAVEI_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        CONSULTAVEI_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/consulta.att_img.png"))); // NOI18N
        CONSULTAVEI_BTN.setText("VEÍCULOS");
        CONSULTAVEI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAVEI_BTNActionPerformed(evt);
            }
        });
        consulta_menu.add(CONSULTAVEI_BTN);

        jMenuBar1.add(consulta_menu);

        excluir_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 110)));
        excluir_menu.setText("EXCLUIR");
        excluir_menu.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        EXCLUIVI_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        EXCLUIVI_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        EXCLUIVI_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excluir_img.png"))); // NOI18N
        EXCLUIVI_BTN.setText("VISITANTE");
        EXCLUIVI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIVI_BTNActionPerformed(evt);
            }
        });
        excluir_menu.add(EXCLUIVI_BTN);

        EXLCUIVEI_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        EXLCUIVEI_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        EXLCUIVEI_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excluir_img.png"))); // NOI18N
        EXLCUIVEI_BTN.setText("VEÍCULO");
        EXLCUIVEI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXLCUIVEI_BTNActionPerformed(evt);
            }
        });
        excluir_menu.add(EXLCUIVEI_BTN);

        jMenuBar1.add(excluir_menu);

        controle_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 110)));
        controle_menu.setText("CONTROLE");
        controle_menu.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        ENTRADAS_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        ENTRADAS_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        ENTRADAS_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/controle_img.png"))); // NOI18N
        ENTRADAS_BTN.setText("ENTRADA");
        ENTRADAS_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTRADAS_BTNActionPerformed(evt);
            }
        });
        controle_menu.add(ENTRADAS_BTN);

        SAIDAS_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SAIDAS_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        SAIDAS_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/controle_img.png"))); // NOI18N
        SAIDAS_BTN.setText("SAÍDA");
        SAIDAS_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIDAS_BTNActionPerformed(evt);
            }
        });
        controle_menu.add(SAIDAS_BTN);

        ESTACIONAMENTO_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        ESTACIONAMENTO_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/estacionamento_img.png"))); // NOI18N
        ESTACIONAMENTO_BTN.setText("ESTACIONAMENTO");
        ESTACIONAMENTO_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESTACIONAMENTO_BTNActionPerformed(evt);
            }
        });
        controle_menu.add(ESTACIONAMENTO_BTN);

        jMenuBar1.add(controle_menu);

        relatorios_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 110)));
        relatorios_menu.setText("RELATÓRIOS");
        relatorios_menu.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        RELATORIOCLI_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        RELATORIOCLI_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/relatorios_img.png"))); // NOI18N
        RELATORIOCLI_BTN.setText("VISITANTES / VEÍCULOS");
        RELATORIOCLI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RELATORIOCLI_BTNActionPerformed(evt);
            }
        });
        relatorios_menu.add(RELATORIOCLI_BTN);

        RELATORIOESTAC_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        RELATORIOESTAC_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/relatorios_img.png"))); // NOI18N
        RELATORIOESTAC_BTN.setText("ESTACIONAMENTO");
        RELATORIOESTAC_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RELATORIOESTAC_BTNActionPerformed(evt);
            }
        });
        relatorios_menu.add(RELATORIOESTAC_BTN);

        RELATORIOFINAN_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        RELATORIOFINAN_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/relatorios_img.png"))); // NOI18N
        RELATORIOFINAN_BTN.setText("FINANÇAS");
        RELATORIOFINAN_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RELATORIOFINAN_BTNActionPerformed(evt);
            }
        });
        relatorios_menu.add(RELATORIOFINAN_BTN);

        RELATORIOFUNC_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        RELATORIOFUNC_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/relatorios_img.png"))); // NOI18N
        RELATORIOFUNC_BTN.setText("FUNCIONÁRIOS");
        RELATORIOFUNC_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RELATORIOFUNC_BTNActionPerformed(evt);
            }
        });
        relatorios_menu.add(RELATORIOFUNC_BTN);

        jMenuBar1.add(relatorios_menu);

        usuarios_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 110)));
        usuarios_menu.setText("USUÁRIOS");
        usuarios_menu.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        CRIAR_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        CRIAR_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        CRIAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usuarios_img.png"))); // NOI18N
        CRIAR_BTN.setText("CRIAR");
        CRIAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRIAR_BTNActionPerformed(evt);
            }
        });
        usuarios_menu.add(CRIAR_BTN);

        GERENCIAR_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        GERENCIAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usuarios_img.png"))); // NOI18N
        GERENCIAR_BTN.setText("GERENCIAR");
        GERENCIAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GERENCIAR_BTNActionPerformed(evt);
            }
        });
        usuarios_menu.add(GERENCIAR_BTN);

        PERMISSOES_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        PERMISSOES_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usuarios_img.png"))); // NOI18N
        PERMISSOES_BTN.setText("PERMISSÕES");
        PERMISSOES_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERMISSOES_BTNActionPerformed(evt);
            }
        });
        usuarios_menu.add(PERMISSOES_BTN);

        jMenuBar1.add(usuarios_menu);

        conf_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 110)));
        conf_menu.setText("CONFIGURAÇÕES");
        conf_menu.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        TEMA_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        TEMA_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/configuracoes_img.png"))); // NOI18N
        TEMA_BTN.setText("TEMA");
        TEMA_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEMA_BTNActionPerformed(evt);
            }
        });
        conf_menu.add(TEMA_BTN);

        DADOS_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        DADOS_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/configuracoes_img.png"))); // NOI18N
        DADOS_BTN.setText("MEUS DADOS");
        DADOS_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DADOS_BTNActionPerformed(evt);
            }
        });
        conf_menu.add(DADOS_BTN);

        SISTEMA_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        SISTEMA_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/informacoes_img.png"))); // NOI18N
        SISTEMA_BTN.setText("SOBRE O SISTEMA");
        SISTEMA_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SISTEMA_BTNActionPerformed(evt);
            }
        });
        conf_menu.add(SISTEMA_BTN);

        TROCAR_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        TROCAR_BTN.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        TROCAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/troca_img.png"))); // NOI18N
        TROCAR_BTN.setText("TROCAR O USUÁRIO");
        TROCAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TROCAR_BTNActionPerformed(evt);
            }
        });
        conf_menu.add(TROCAR_BTN);

        jMenuBar1.add(conf_menu);

        SAIR_BTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 110), 2));
        SAIR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sair_img.png"))); // NOI18N
        SAIR_BTN.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        SAIR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAIR_BTNMouseClicked(evt);
            }
        });
        SAIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTNActionPerformed(evt);
            }
        });
        SAIR_BTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SAIR_BTNKeyPressed(evt);
            }
        });
        jMenuBar1.add(SAIR_BTN);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CADASTROVI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTROVI_BTNActionPerformed
        new CadastroVI_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CADASTROVI_BTNActionPerformed

    private void CONSULTAVI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAVI_BTNActionPerformed
        new ConsultaATTVI_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CONSULTAVI_BTNActionPerformed

    private void RELATORIOESTAC_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RELATORIOESTAC_BTNActionPerformed
        new Manutenção_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RELATORIOESTAC_BTNActionPerformed

    private void RELATORIOFINAN_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RELATORIOFINAN_BTNActionPerformed
        new Manutenção_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RELATORIOFINAN_BTNActionPerformed

    private void GERENCIAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GERENCIAR_BTNActionPerformed
        new GerenciarUsuario_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GERENCIAR_BTNActionPerformed

    private void SAIR_BTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SAIR_BTNKeyPressed

    }//GEN-LAST:event_SAIR_BTNKeyPressed

    private void SAIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTNActionPerformed

    }//GEN-LAST:event_SAIR_BTNActionPerformed

    private void SAIR_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAIR_BTNMouseClicked
        int resp = JOptionPane.showConfirmDialog(
            this,
                "Deseja realmente sair?",
                "Encerrar Sessão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
            null // aqui você pode colocar um ícone, se quiser
        );
        if (resp == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_SAIR_BTNMouseClicked

    private void CADASTROVEI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTROVEI_BTNActionPerformed
        new CadastroVEI_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CADASTROVEI_BTNActionPerformed

    private void CONSULTAVEI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAVEI_BTNActionPerformed
        new ConsultaATTVEI_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CONSULTAVEI_BTNActionPerformed

    private void EXLCUIVEI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXLCUIVEI_BTNActionPerformed
        new ExcluirVEI_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EXLCUIVEI_BTNActionPerformed

    private void TROCAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TROCAR_BTNActionPerformed
        new Login_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TROCAR_BTNActionPerformed

    private void panelImage1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelImage1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_E) {
            SAIR_BTN.doClick();
        }
    }//GEN-LAST:event_panelImage1KeyPressed

    private void EXCLUIVI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIVI_BTNActionPerformed
        new ExcluirVI_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EXCLUIVI_BTNActionPerformed

    private void ENTRADAS_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTRADAS_BTNActionPerformed
        new Entrada_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ENTRADAS_BTNActionPerformed

    private void SAIDAS_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIDAS_BTNActionPerformed
        new Saida_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SAIDAS_BTNActionPerformed

    private void CRIAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRIAR_BTNActionPerformed
        new CriarUsuario_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CRIAR_BTNActionPerformed

    private void RELATORIOCLI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RELATORIOCLI_BTNActionPerformed
        new RELVisitantes_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RELATORIOCLI_BTNActionPerformed

    private void RELATORIOFUNC_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RELATORIOFUNC_BTNActionPerformed
        new Manutenção_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RELATORIOFUNC_BTNActionPerformed

    private void PERMISSOES_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERMISSOES_BTNActionPerformed
        new Manutenção_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PERMISSOES_BTNActionPerformed

    private void TEMA_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEMA_BTNActionPerformed
        new Manutenção_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TEMA_BTNActionPerformed

    private void DADOS_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DADOS_BTNActionPerformed
        new Manutenção_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DADOS_BTNActionPerformed

    private void SISTEMA_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SISTEMA_BTNActionPerformed
        new Manutenção_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SISTEMA_BTNActionPerformed

    private void ESTACIONAMENTO_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESTACIONAMENTO_BTNActionPerformed
        new Manutenção_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ESTACIONAMENTO_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CADASTROVEI_BTN;
    private javax.swing.JMenuItem CADASTROVI_BTN;
    private javax.swing.JMenuItem CONSULTAVEI_BTN;
    private javax.swing.JMenuItem CONSULTAVI_BTN;
    private javax.swing.JMenuItem CRIAR_BTN;
    private javax.swing.JMenuItem DADOS_BTN;
    private javax.swing.JMenuItem ENTRADAS_BTN;
    private javax.swing.JMenuItem ESTACIONAMENTO_BTN;
    private javax.swing.JMenuItem EXCLUIVI_BTN;
    private javax.swing.JMenuItem EXLCUIVEI_BTN;
    private javax.swing.JMenuItem GERENCIAR_BTN;
    private javax.swing.JMenuItem PERMISSOES_BTN;
    private javax.swing.JMenuItem RELATORIOCLI_BTN;
    private javax.swing.JMenuItem RELATORIOESTAC_BTN;
    private javax.swing.JMenuItem RELATORIOFINAN_BTN;
    private javax.swing.JMenuItem RELATORIOFUNC_BTN;
    private javax.swing.JMenuItem SAIDAS_BTN;
    public static javax.swing.JMenu SAIR_BTN;
    private javax.swing.JMenuItem SISTEMA_BTN;
    private javax.swing.JMenuItem TEMA_BTN;
    private javax.swing.JMenuItem TROCAR_BTN;
    private javax.swing.JMenu cadastro_menu;
    private javax.swing.JLabel cargo_lbl;
    private javax.swing.JMenu conf_menu;
    private javax.swing.JMenu consulta_menu;
    private javax.swing.JMenu controle_menu;
    private javax.swing.JLabel data_lbl;
    private javax.swing.JMenu excluir_menu;
    private javax.swing.JLabel hora_lbl;
    private javax.swing.JMenuBar jMenuBar1;
    private org.edisoncor.gui.label.LabelCustom labelCustom1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JMenu relatorios_menu;
    private javax.swing.JLabel usuario_lbl;
    private javax.swing.JMenu usuarios_menu;
    // End of variables declaration//GEN-END:variables
}
