/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Saida_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Saida_GUI
     */
    public Saida_GUI() {
        initComponents();
        colaborador_txt.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        VOLTAR_BTN = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel6 = new javax.swing.JLabel();
        placa_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel7 = new javax.swing.JLabel();
        modelo_txt = new org.edisoncor.gui.textField.TextFieldRound();
        cor_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel10 = new javax.swing.JLabel();
        CANCELAR_BTN = new org.edisoncor.gui.button.ButtonRound();
        SAIDA_BTN = new org.edisoncor.gui.button.ButtonRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BUSCARINFO_BTN = new org.edisoncor.gui.panel.PanelImage();
        jLabel13 = new javax.swing.JLabel();
        colaborador_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel15 = new javax.swing.JLabel();
        datasaidavei_txt = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel23 = new javax.swing.JLabel();
        horasaidavei_txt = new org.edisoncor.gui.textField.TextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 74), 4, true));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("S A Í D A");

        VOLTAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/voltar_img.png"))); // NOI18N
        VOLTAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLTAR_BTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VOLTAR_BTNLayout = new javax.swing.GroupLayout(VOLTAR_BTN);
        VOLTAR_BTN.setLayout(VOLTAR_BTNLayout);
        VOLTAR_BTNLayout.setHorizontalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        VOLTAR_BTNLayout.setVerticalGroup(
            VOLTAR_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(VOLTAR_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(4, 4, 792, 80);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.rodape_img.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(4, 496, 792, 100);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("*Placa:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 230, 50, 24);

        placa_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa_txtActionPerformed(evt);
            }
        });
        placa_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                placa_txtKeyPressed(evt);
            }
        });
        jPanel1.add(placa_txt);
        placa_txt.setBounds(120, 230, 125, 24);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Modelo:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(290, 230, 60, 24);

        modelo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelo_txtActionPerformed(evt);
            }
        });
        modelo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modelo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(modelo_txt);
        modelo_txt.setBounds(360, 230, 125, 24);

        cor_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cor_txtActionPerformed(evt);
            }
        });
        cor_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cor_txtKeyPressed(evt);
            }
        });
        jPanel1.add(cor_txt);
        cor_txt.setBounds(570, 230, 125, 24);

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cor:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(520, 230, 30, 24);

        CANCELAR_BTN.setBackground(new java.awt.Color(33, 63, 110));
        CANCELAR_BTN.setText("CANCELAR");
        CANCELAR_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        CANCELAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CANCELAR_BTNMouseEntered(evt);
            }
        });
        CANCELAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CANCELAR_BTN);
        CANCELAR_BTN.setBounds(150, 430, 150, 35);

        SAIDA_BTN.setBackground(new java.awt.Color(33, 63, 110));
        SAIDA_BTN.setText("SAÍDA");
        SAIDA_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        SAIDA_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SAIDA_BTNMouseEntered(evt);
            }
        });
        SAIDA_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIDA_BTNActionPerformed(evt);
            }
        });
        SAIDA_BTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SAIDA_BTNKeyPressed(evt);
            }
        });
        jPanel1.add(SAIDA_BTN);
        SAIDA_BTN.setBounds(480, 430, 150, 35);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SAÍDA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 290, 104, 24);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VEÍCULO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 170, 97, 24);

        BUSCARINFO_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscarinfo_img.png"))); // NOI18N
        BUSCARINFO_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BUSCARINFO_BTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BUSCARINFO_BTNMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout BUSCARINFO_BTNLayout = new javax.swing.GroupLayout(BUSCARINFO_BTN);
        BUSCARINFO_BTN.setLayout(BUSCARINFO_BTNLayout);
        BUSCARINFO_BTNLayout.setHorizontalGroup(
            BUSCARINFO_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        BUSCARINFO_BTNLayout.setVerticalGroup(
            BUSCARINFO_BTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(BUSCARINFO_BTN);
        BUSCARINFO_BTN.setBounds(720, 220, 40, 40);

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Colaborador:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(280, 120, 90, 24);

        colaborador_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaborador_txtActionPerformed(evt);
            }
        });
        colaborador_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                colaborador_txtKeyPressed(evt);
            }
        });
        jPanel1.add(colaborador_txt);
        colaborador_txt.setBounds(380, 120, 125, 24);

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Data:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(200, 360, 40, 24);

        datasaidavei_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datasaidavei_txtActionPerformed(evt);
            }
        });
        datasaidavei_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datasaidavei_txtKeyPressed(evt);
            }
        });
        jPanel1.add(datasaidavei_txt);
        datasaidavei_txt.setBounds(250, 360, 125, 24);

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Hora:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(410, 360, 40, 24);

        horasaidavei_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasaidavei_txtActionPerformed(evt);
            }
        });
        horasaidavei_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                horasaidavei_txtKeyPressed(evt);
            }
        });
        jPanel1.add(horasaidavei_txt);
        horasaidavei_txt.setBounds(460, 360, 125, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VOLTAR_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTAR_BTNMouseClicked
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTAR_BTNMouseClicked

    private void placa_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placa_txtActionPerformed

    private void placa_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placa_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            modelo_txt.requestFocus();
        }
    }//GEN-LAST:event_placa_txtKeyPressed

    private void modelo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelo_txtActionPerformed

    private void modelo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelo_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            cor_txt.requestFocus();
        }
    }//GEN-LAST:event_modelo_txtKeyPressed

    private void cor_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cor_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cor_txtActionPerformed

    private void cor_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cor_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            datasaidavei_txt.requestFocus();
        }
    }//GEN-LAST:event_cor_txtKeyPressed

    private void CANCELAR_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELAR_BTNMouseEntered
        CANCELAR_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CANCELAR_BTNMouseEntered

    private void CANCELAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELAR_BTNActionPerformed
        placa_txt.setText("");
        modelo_txt.setText("");
        cor_txt.setText("");
        datasaidavei_txt.setText("");
        colaborador_txt.setText("");
    }//GEN-LAST:event_CANCELAR_BTNActionPerformed

    private void SAIDA_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAIDA_BTNMouseEntered
        SAIDA_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_SAIDA_BTNMouseEntered

    private void SAIDA_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIDA_BTNActionPerformed
        String placa = placa_txt.getText().trim();
    String modelo = modelo_txt.getText().trim();
    String cor = cor_txt.getText().trim();
    String colaborador = colaborador_txt.getText().trim();

    if (placa.isEmpty() || modelo.isEmpty() || colaborador.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        return;
    }

    boolean sucesso = Controller.Saida_DAO.registrarSaida(placa, modelo, cor, colaborador);

    if (sucesso) {
        JOptionPane.showMessageDialog(this, "Saída registrada com sucesso!");
        placa_txt.setText("");
        modelo_txt.setText("");
        cor_txt.setText("");
        colaborador_txt.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao registrar saída!");
    }
    }//GEN-LAST:event_SAIDA_BTNActionPerformed

    private void SAIDA_BTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SAIDA_BTNKeyPressed

    }//GEN-LAST:event_SAIDA_BTNKeyPressed

    private void colaborador_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaborador_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colaborador_txtActionPerformed

    private void colaborador_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colaborador_txtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            placa_txt.requestFocus();
        }
    }//GEN-LAST:event_colaborador_txtKeyPressed

    private void BUSCARINFO_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUSCARINFO_BTNMouseClicked
        String placa = placa_txt.getText().trim();

    if (placa.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite a placa do veículo!");
        return;
    }

    String[] veiculo = Controller.Saida_DAO.buscarVeiculo(placa);
    if (veiculo != null) {
        modelo_txt.setText(veiculo[0]);
        cor_txt.setText(veiculo[1]);
        colaborador_txt.setText(veiculo[2]);
    } else {
        JOptionPane.showMessageDialog(this, "Veículo não encontrado!");
    }
    }//GEN-LAST:event_BUSCARINFO_BTNMouseClicked

    private void datasaidavei_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datasaidavei_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datasaidavei_txtActionPerformed

    private void datasaidavei_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datasaidavei_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_datasaidavei_txtKeyPressed

    private void horasaidavei_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasaidavei_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasaidavei_txtActionPerformed

    private void horasaidavei_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horasaidavei_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasaidavei_txtKeyPressed

    private void BUSCARINFO_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUSCARINFO_BTNMouseEntered
        BUSCARINFO_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BUSCARINFO_BTNMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saida_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saida_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saida_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saida_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saida_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage BUSCARINFO_BTN;
    private org.edisoncor.gui.button.ButtonRound CANCELAR_BTN;
    private org.edisoncor.gui.button.ButtonRound SAIDA_BTN;
    private org.edisoncor.gui.panel.PanelImage VOLTAR_BTN;
    private org.edisoncor.gui.textField.TextFieldRound colaborador_txt;
    private org.edisoncor.gui.textField.TextFieldRound cor_txt;
    private org.edisoncor.gui.textField.TextFieldRound datasaidavei_txt;
    private org.edisoncor.gui.textField.TextFieldRound horasaidavei_txt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.textField.TextFieldRound modelo_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.textField.TextFieldRound placa_txt;
    // End of variables declaration//GEN-END:variables
}
